//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concepto.Packages.KBDoctorCore {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Concepto.Packages.KBDoctorCore.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About KBDoctor.
        /// </summary>
        internal static string AboutKBDoctor {
            get {
                return ResourceManager.GetString("AboutKBDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add IN: to parametrs without IN:/OUT:/INOUT:.
        /// </summary>
        internal static string AddINParmRule {
            get {
                return ResourceManager.GetString("AddINParmRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Char that should be VarChar.
        /// </summary>
        internal static string AttCharToVarchar {
            get {
                return ResourceManager.GetString("AttCharToVarchar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description attribute without unique index.
        /// </summary>
        internal static string AttDescWithoutUniqueIndex {
            get {
                return ResourceManager.GetString("AttDescWithoutUniqueIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List attributes Formula.
        /// </summary>
        internal static string AttFormula {
            get {
                return ResourceManager.GetString("AttFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attributes only in transactions.
        /// </summary>
        internal static string AttInOneTrnOnly {
            get {
                return ResourceManager.GetString("AttInOneTrnOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attributes Key and Varchar.
        /// </summary>
        internal static string AttKeyVarchar {
            get {
                return ResourceManager.GetString("AttKeyVarchar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not referenced by any reachable object.
        /// </summary>
        internal static string AttNotReferenced {
            get {
                return ResourceManager.GetString("AttNotReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Where is updated this attribute? .
        /// </summary>
        internal static string AttUpdated {
            get {
                return ResourceManager.GetString("AttUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VarChar that shoud be Char.
        /// </summary>
        internal static string AttVarcharToChar {
            get {
                return ResourceManager.GetString("AttVarcharToChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a With no description.
        /// </summary>
        internal static string AttWithNoDescription {
            get {
                return ResourceManager.GetString("AttWithNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Without domain.
        /// </summary>
        internal static string AttWithNoDomain {
            get {
                return ResourceManager.GetString("AttWithNoDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove attribute with no table.
        /// </summary>
        internal static string AttWithoutBaseTable {
            get {
                return ResourceManager.GetString("AttWithoutBaseTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Without column title.
        /// </summary>
        internal static string AttWithoutColumnTitle {
            get {
                return ResourceManager.GetString("AttWithoutColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a With incomplete description or title.
        /// </summary>
        internal static string AttWithoutDescription {
            get {
                return ResourceManager.GetString("AttWithoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Without title.
        /// </summary>
        internal static string AttWithoutTitle {
            get {
                return ResourceManager.GetString("AttWithoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Build Module Objects and References.
        /// </summary>
        internal static string BuildModule {
            get {
                return ResourceManager.GetString("BuildModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Build Object and References.
        /// </summary>
        internal static string BuildObjectAndReferences {
            get {
                return ResourceManager.GetString("BuildObjectAndReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate objects in text files.
        /// </summary>
        internal static string CalculateCheckSum {
            get {
                return ResourceManager.GetString("CalculateCheckSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change code to improve readability.
        /// </summary>
        internal static string ChangeLegacyCode {
            get {
                return ResourceManager.GetString("ChangeLegacyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Class not in Theme and Class not used.
        /// </summary>
        internal static string ClassNotInTheme {
            get {
                return ResourceManager.GetString("ClassNotInTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Classes Used.
        /// </summary>
        internal static string ClassUsed {
            get {
                return ResourceManager.GetString("ClassUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clean my KB as much as possible.
        /// </summary>
        internal static string CleanKBAsMuchAsPossible {
            get {
                return ResourceManager.GetString("CleanKBAsMuchAsPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Initialize and clean objects.
        /// </summary>
        internal static string CleanObjects {
            get {
                return ResourceManager.GetString("CleanObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clean variables not used.
        /// </summary>
        internal static string CleanVarsNotUsed {
            get {
                return ResourceManager.GetString("CleanVarsNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compare Navigations (two last snapshots).
        /// </summary>
        internal static string CompareLastNVGDirectory {
            get {
                return ResourceManager.GetString("CompareLastNVGDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compare Objects in text format (two last snapshots).
        /// </summary>
        internal static string CompareLastOBJDirectory {
            get {
                return ResourceManager.GetString("CompareLastOBJDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List objects not generated by patterns.
        /// </summary>
        internal static string CountGeneratedByPattern {
            get {
                return ResourceManager.GetString("CountGeneratedByPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #Table access x object.
        /// </summary>
        internal static string CountTableAccess {
            get {
                return ResourceManager.GetString("CountTableAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit  code to replace.
        /// </summary>
        internal static string EditLegacyCodeToReplace {
            get {
                return ResourceManager.GetString("EditLegacyCodeToReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate KB Graphs.
        /// </summary>
        internal static string GenerateGraph {
            get {
                return ResourceManager.GetString("GenerateGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate Location.XML.
        /// </summary>
        internal static string GenerateLocationXML {
            get {
                return ResourceManager.GetString("GenerateLocationXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate Simple Trn from Not Generate Transactions.
        /// </summary>
        internal static string GenerateSimpleTransactionFromNotGeneratedTransactions {
            get {
                return ResourceManager.GetString("GenerateSimpleTransactionFromNotGeneratedTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate scripts to check data.
        /// </summary>
        internal static string GenerateSQLScripts {
            get {
                return ResourceManager.GetString("GenerateSQLScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate transactions from tables.
        /// </summary>
        internal static string GenerateTrnFromTable {
            get {
                return ResourceManager.GetString("GenerateTrnFromTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtype groups with incomplete description.
        /// </summary>
        internal static string GroupWithNoDescription {
            get {
                return ResourceManager.GetString("GroupWithNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a KBDoctor Help (in Spanish).
        /// </summary>
        internal static string HelpKBDoctor {
            get {
                return ResourceManager.GetString("HelpKBDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a With not referenced attributes.
        /// </summary>
        internal static string IndexWithNotRefAtt {
            get {
                return ResourceManager.GetString("IndexWithNotRefAtt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /*
        /// * jQuery 1.2.3 - New Wave Javascript
        /// *
        /// * Copyright (c) 2008 John Resig (jquery.com)
        /// * Dual licensed under the MIT (MIT-LICENSE.txt)
        /// * and GPL (GPL-LICENSE.txt) licenses.
        /// *
        /// * $Date: 2008-02-06 00:21:25 -0500 (Wed, 06 Feb 2008) $
        /// * $Rev: 4663 $
        /// */
        ///(function(){if(window.jQuery)var _jQuery=window.jQuery;var jQuery=window.jQuery=function(selector,context){return new jQuery.prototype.init(selector,context);};if(window.$)var _$=window.$;window.$=jQuery;var quickExpr=/^[^&lt;]*(&lt;(.|\s)+&gt;)[^&gt;]*$|^ [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string jquery_latest {
            get {
                return ResourceManager.GetString("jquery_latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /*
        /// * 
        /// * TableSorter 2.0 - Client-side table sorting with ease!
        /// * Version 2.0.5b
        /// * @requires jQuery v1.2.3
        /// * 
        /// * Copyright (c) 2007 Christian Bach
        /// * Examples and docs at: http://tablesorter.com
        /// * Dual licensed under the MIT and GPL licenses:
        /// * http://www.opensource.org/licenses/mit-license.php
        /// * http://www.gnu.org/licenses/gpl.html
        /// * 
        /// */
        ////**
        /// * 
        /// * @description Create a sortable table with multi-column sorting capabilitys
        /// * 
        /// * @example $(&apos;table&apos;).tablesorter();
        /// * @desc Create  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string jquery_tablesorter {
            get {
                return ResourceManager.GetString("jquery_tablesorter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a KB Interfaces.
        /// </summary>
        internal static string KBInterfaces {
            get {
                return ResourceManager.GetString("KBInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List system public URI/URL.
        /// </summary>
        internal static string ListAPIObjects {
            get {
                return ResourceManager.GetString("ListAPIObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List Attributes.
        /// </summary>
        internal static string ListAttributes {
            get {
                return ResourceManager.GetString("ListAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List classes used.
        /// </summary>
        internal static string ListClassUsed {
            get {
                return ResourceManager.GetString("ListClassUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List Domains.
        /// </summary>
        internal static string ListDomain {
            get {
                return ResourceManager.GetString("ListDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List last KBDoctor reports.
        /// </summary>
        internal static string ListLastReports {
            get {
                return ResourceManager.GetString("ListLastReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List Modules Errors.
        /// </summary>
        internal static string ListModules {
            get {
                return ResourceManager.GetString("ListModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List Modules Statistics.
        /// </summary>
        internal static string ListModulesStatistics {
            get {
                return ResourceManager.GetString("ListModulesStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List Objects.
        /// </summary>
        internal static string ListObj {
            get {
                return ResourceManager.GetString("ListObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List tables in modules.
        /// </summary>
        internal static string ListObjectsWithTableInOtherModule {
            get {
                return ResourceManager.GetString("ListObjectsWithTableInOtherModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find Similar Navigations.
        /// </summary>
        internal static string ListObjSimilarNavigation {
            get {
                return ResourceManager.GetString("ListObjSimilarNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objects with warnings and errors.
        /// </summary>
        internal static string ListObjWarningsErrors {
            get {
                return ResourceManager.GetString("ListObjWarningsErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Webpanels and Transactions called by Procedures.
        /// </summary>
        internal static string ListProcedureCallWebpanelTransaction {
            get {
                return ResourceManager.GetString("ListProcedureCallWebpanelTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List tables/attributes using domain.
        /// </summary>
        internal static string ListTableAttributesUsingDomain {
            get {
                return ResourceManager.GetString("ListTableAttributesUsingDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List Tables.
        /// </summary>
        internal static string ListTables {
            get {
                return ResourceManager.GetString("ListTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List tables in modules.
        /// </summary>
        internal static string ListTablesInModules {
            get {
                return ResourceManager.GetString("ListTablesInModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tables used by mains.
        /// </summary>
        internal static string MainTableUsed {
            get {
                return ResourceManager.GetString("MainTableUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mark Public Objects.
        /// </summary>
        internal static string MarkPublicObjects {
            get {
                return ResourceManager.GetString("MarkPublicObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modules dependencies.
        /// </summary>
        internal static string ModuleDependencies {
            get {
                return ResourceManager.GetString("ModuleDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Move Transactions to Folders.
        /// </summary>
        internal static string MoveTransactions {
            get {
                return ResourceManager.GetString("MoveTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complex Specification Objects.
        /// </summary>
        internal static string ObjectsComplex {
            get {
                return ResourceManager.GetString("ObjectsComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objects Diagnostics.
        /// </summary>
        internal static string ObjectsDiagnostics {
            get {
                return ResourceManager.GetString("ObjectsDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objects with legacy code.
        /// </summary>
        internal static string ObjectsLegacyCode {
            get {
                return ResourceManager.GetString("ObjectsLegacyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mains called by others.
        /// </summary>
        internal static string ObjectsMainCalled {
            get {
                return ResourceManager.GetString("ObjectsMainCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove not referenced objects.
        /// </summary>
        internal static string ObjectsNotCalled {
            get {
                return ResourceManager.GetString("ObjectsNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mark unreachable objects with GenerateObject=FALSE.
        /// </summary>
        internal static string ObjectsNotReacheable {
            get {
                return ResourceManager.GetString("ObjectsNotReacheable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculate KBDoctor complexity index.
        /// </summary>
        internal static string ObjectsRefactoringCandidates {
            get {
                return ResourceManager.GetString("ObjectsRefactoringCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List all object dependencies.
        /// </summary>
        internal static string ObjectsReferenced {
            get {
                return ResourceManager.GetString("ObjectsReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generated for WIN and WEB.
        /// </summary>
        internal static string ObjectsWINWEB {
            get {
                return ResourceManager.GetString("ObjectsWINWEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a With parm() and Commit on exit=Yes.
        /// </summary>
        internal static string ObjectsWithCommitOnExit {
            get {
                return ResourceManager.GetString("ObjectsWithCommitOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a With parm() without in:/out:/inout:.
        /// </summary>
        internal static string ObjectsWithoutInOut {
            get {
                return ResourceManager.GetString("ObjectsWithoutInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a With variables not based on attribute/domain.
        /// </summary>
        internal static string ObjectsWithVarNotBasedOnAtt {
            get {
                return ResourceManager.GetString("ObjectsWithVarNotBasedOnAtt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objects with variables not used.
        /// </summary>
        internal static string ObjectsWithVarsNotUsed {
            get {
                return ResourceManager.GetString("ObjectsWithVarsNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open navigation folder.
        /// </summary>
        internal static string OpenFolderComparerNavigation {
            get {
                return ResourceManager.GetString("OpenFolderComparerNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open object  in text format folder.
        /// </summary>
        internal static string OpenFolderObjComparerNavigation {
            get {
                return ResourceManager.GetString("OpenFolderObjComparerNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forced generation of SDT .
        /// </summary>
        internal static string PrcCalledByTrn {
            get {
                return ResourceManager.GetString("PrcCalledByTrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create a snapshot of navigations.
        /// </summary>
        internal static string PrepareComparerNavigation {
            get {
                return ResourceManager.GetString("PrepareComparerNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate Get/Set Procedures.
        /// </summary>
        internal static string ProcedureGetSet {
            get {
                return ResourceManager.GetString("ProcedureGetSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate SDT Sources.
        /// </summary>
        internal static string ProcedureSDT {
            get {
                return ResourceManager.GetString("ProcedureSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recommended Module.
        /// </summary>
        internal static string RecomendedModule {
            get {
                return ResourceManager.GetString("RecomendedModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removable Transactions.
        /// </summary>
        internal static string RemovableTransactions {
            get {
                return ResourceManager.GetString("RemovableTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rename Objects to significant name length.
        /// </summary>
        internal static string RenameAttributesAndTables {
            get {
                return ResourceManager.GetString("RenameAttributesAndTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Replace Domain.
        /// </summary>
        internal static string ReplaceDomain {
            get {
                return ResourceManager.GetString("ReplaceDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change attributes with Nullable=Compatible.
        /// </summary>
        internal static string ReplaceNullCompatible {
            get {
                return ResourceManager.GetString("ReplaceNullCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset all transaction and workpanel WIN Forms.
        /// </summary>
        internal static string ResetWINForm {
            get {
                return ResourceManager.GetString("ResetWINForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search and Replace in Objects.
        /// </summary>
        internal static string SearchAndReplace {
            get {
                return ResourceManager.GetString("SearchAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&apos;1.0&apos;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;xsl:output method=&quot;text&quot;/&gt;
        ///
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;xsl:text&gt;Text Format Navigation for KBDoctor version 10.8&lt;/xsl:text&gt;
        ///    &lt;xsl:apply-templates select=&quot;ObjectSpec&quot;/&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;xsl:variable name=&quot;Product&quot; select=&quot;KBdoctor&quot;/&gt;
        ///  &lt;xsl:variable name=&quot;Images&quot;  select=&quot;Images&quot;/&gt;
        ///
        ///  &lt;xsl:template name=&quot;TableHeaderMain&quot;&gt;
        ///    &lt;xsl:param name=&quot;title&quot;&gt;Table Title&lt;/xsl:param&gt;
        ///    [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string specXEv2 {
            get {
                return ResourceManager.GetString("specXEv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Split main object.
        /// </summary>
        internal static string SplitMainObject {
            get {
                return ResourceManager.GetString("SplitMainObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New - Attribute not instanciated.
        /// </summary>
        internal static string TableInsertNew {
            get {
                return ResourceManager.GetString("TableInsertNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Table&apos;s width.
        /// </summary>
        internal static string TablesWidth {
            get {
                return ResourceManager.GetString("TablesWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tables with incomplete description.
        /// </summary>
        internal static string TablesWithNoDescription {
            get {
                return ResourceManager.GetString("TablesWithNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Table &lt;-&gt; Transaction Relation.
        /// </summary>
        internal static string TableTransaction {
            get {
                return ResourceManager.GetString("TableTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Table - Update/Insert/Delete/Read.
        /// </summary>
        internal static string TableUpdate {
            get {
                return ResourceManager.GetString("TableUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tree call - Commit.
        /// </summary>
        internal static string TreeCommit {
            get {
                return ResourceManager.GetString("TreeCommit", resourceCulture);
            }
        }
    }
}
