//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concepto.Packages.KBDoctor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Concepto.Packages.KBDoctor.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About KBDoctor.
        /// </summary>
        internal static string AboutKBDoctor {
            get {
                return ResourceManager.GetString("AboutKBDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add IN: to parametrs without IN:/OUT:/INOUT:.
        /// </summary>
        internal static string AddINParmRule {
            get {
                return ResourceManager.GetString("AddINParmRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Type Comparer.
        /// </summary>
        internal static string AssignTypeComparer {
            get {
                return ResourceManager.GetString("AssignTypeComparer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Char that should be VarChar.
        /// </summary>
        internal static string AttCharToVarchar {
            get {
                return ResourceManager.GetString("AttCharToVarchar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description attribute without unique index.
        /// </summary>
        internal static string AttDescWithoutUniqueIndex {
            get {
                return ResourceManager.GetString("AttDescWithoutUniqueIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List attributes Formula.
        /// </summary>
        internal static string AttFormula {
            get {
                return ResourceManager.GetString("AttFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes only in transactions.
        /// </summary>
        internal static string AttInOneTrnOnly {
            get {
                return ResourceManager.GetString("AttInOneTrnOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes Key and Varchar.
        /// </summary>
        internal static string AttKeyVarchar {
            get {
                return ResourceManager.GetString("AttKeyVarchar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not referenced by any reachable object.
        /// </summary>
        internal static string AttNotReferenced {
            get {
                return ResourceManager.GetString("AttNotReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is updated this attribute? .
        /// </summary>
        internal static string AttUpdated {
            get {
                return ResourceManager.GetString("AttUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VarChar that shoud be Char.
        /// </summary>
        internal static string AttVarcharToChar {
            get {
                return ResourceManager.GetString("AttVarcharToChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With no description.
        /// </summary>
        internal static string AttWithNoDescription {
            get {
                return ResourceManager.GetString("AttWithNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without domain.
        /// </summary>
        internal static string AttWithNoDomain {
            get {
                return ResourceManager.GetString("AttWithNoDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove attribute with no table.
        /// </summary>
        internal static string AttWithoutBaseTable {
            get {
                return ResourceManager.GetString("AttWithoutBaseTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without column title.
        /// </summary>
        internal static string AttWithoutColumnTitle {
            get {
                return ResourceManager.GetString("AttWithoutColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With incomplete description or title.
        /// </summary>
        internal static string AttWithoutDescription {
            get {
                return ResourceManager.GetString("AttWithoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without title.
        /// </summary>
        internal static string AttWithoutTitle {
            get {
                return ResourceManager.GetString("AttWithoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Module Objects and References.
        /// </summary>
        internal static string BuildModule {
            get {
                return ResourceManager.GetString("BuildModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Object and References.
        /// </summary>
        internal static string BuildObjectAndReferences {
            get {
                return ResourceManager.GetString("BuildObjectAndReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build objects with property.
        /// </summary>
        internal static string BuildObjectWithProperty {
            get {
                return ResourceManager.GetString("BuildObjectWithProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate objects in text files.
        /// </summary>
        internal static string CalculateCheckSum {
            get {
                return ResourceManager.GetString("CalculateCheckSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change code to improve readability.
        /// </summary>
        internal static string ChangeLegacyCode {
            get {
                return ResourceManager.GetString("ChangeLegacyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class not in Theme and Class not used.
        /// </summary>
        internal static string ClassNotInTheme {
            get {
                return ResourceManager.GetString("ClassNotInTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes Used.
        /// </summary>
        internal static string ClassUsed {
            get {
                return ResourceManager.GetString("ClassUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean my KB as much as possible.
        /// </summary>
        internal static string CleanKBAsMuchAsPossible {
            get {
                return ResourceManager.GetString("CleanKBAsMuchAsPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize and clean objects.
        /// </summary>
        internal static string CleanObjects {
            get {
                return ResourceManager.GetString("CleanObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean variables not used.
        /// </summary>
        internal static string CleanVarsNotUsed {
            get {
                return ResourceManager.GetString("CleanVarsNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Navigations (two last snapshots).
        /// </summary>
        internal static string CompareLastNVGDirectory {
            get {
                return ResourceManager.GetString("CompareLastNVGDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Objects in text format (two last snapshots).
        /// </summary>
        internal static string CompareLastOBJDirectory {
            get {
                return ResourceManager.GetString("CompareLastOBJDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constants in code.
        /// </summary>
        internal static string ConstantsInCode {
            get {
                return ResourceManager.GetString("ConstantsInCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List objects not generated by patterns.
        /// </summary>
        internal static string CountGeneratedByPattern {
            get {
                return ResourceManager.GetString("CountGeneratedByPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count table access.
        /// </summary>
        internal static string CountTableAccess {
            get {
                return ResourceManager.GetString("CountTableAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit  code to replace.
        /// </summary>
        internal static string EditLegacyCodeToReplace {
            get {
                return ResourceManager.GetString("EditLegacyCodeToReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit review objects ini file.
        /// </summary>
        internal static string EditReviewObjects {
            get {
                return ResourceManager.GetString("EditReviewObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Conditional Blocks.
        /// </summary>
        internal static string EmptyConditionalBlocks {
            get {
                return ResourceManager.GetString("EmptyConditionalBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Each without When None.
        /// </summary>
        internal static string ForEachsWithoutWhenNone {
            get {
                return ResourceManager.GetString("ForEachsWithoutWhenNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate KB Graphs.
        /// </summary>
        internal static string GenerateGraph {
            get {
                return ResourceManager.GetString("GenerateGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Location.XML.
        /// </summary>
        internal static string GenerateLocationXML {
            get {
                return ResourceManager.GetString("GenerateLocationXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Simple Trn from Not Generate Transactions.
        /// </summary>
        internal static string GenerateSimpleTransactionFromNotGeneratedTransactions {
            get {
                return ResourceManager.GetString("GenerateSimpleTransactionFromNotGeneratedTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate scripts to check data.
        /// </summary>
        internal static string GenerateSQLScripts {
            get {
                return ResourceManager.GetString("GenerateSQLScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate transactions from tables.
        /// </summary>
        internal static string GenerateTrnFromTable {
            get {
                return ResourceManager.GetString("GenerateTrnFromTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtype groups with incomplete description.
        /// </summary>
        internal static string GroupWithNoDescription {
            get {
                return ResourceManager.GetString("GroupWithNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KBDoctor Help (in Spanish).
        /// </summary>
        internal static string HelpKBDoctor {
            get {
                return ResourceManager.GetString("HelpKBDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index with not referenced attributes.
        /// </summary>
        internal static string IndexWithNotRefAtt {
            get {
                return ResourceManager.GetString("IndexWithNotRefAtt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB Interfaces.
        /// </summary>
        internal static string KBInterfaces {
            get {
                return ResourceManager.GetString("KBInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List system public URI/URL.
        /// </summary>
        internal static string ListAPIObjects {
            get {
                return ResourceManager.GetString("ListAPIObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Attributes.
        /// </summary>
        internal static string ListAttributes {
            get {
                return ResourceManager.GetString("ListAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List classes used.
        /// </summary>
        internal static string ListClassUsed {
            get {
                return ResourceManager.GetString("ListClassUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Domains.
        /// </summary>
        internal static string ListDomain {
            get {
                return ResourceManager.GetString("ListDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List last KBDoctor reports.
        /// </summary>
        internal static string ListLastReports {
            get {
                return ResourceManager.GetString("ListLastReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Modules Errors.
        /// </summary>
        internal static string ListModules {
            get {
                return ResourceManager.GetString("ListModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Modules Statistics.
        /// </summary>
        internal static string ListModulesStatistics {
            get {
                return ResourceManager.GetString("ListModulesStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Objects.
        /// </summary>
        internal static string ListObj {
            get {
                return ResourceManager.GetString("ListObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Similar Navigations.
        /// </summary>
        internal static string ListObjSimilarNavigation {
            get {
                return ResourceManager.GetString("ListObjSimilarNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects with warnings and errors.
        /// </summary>
        internal static string ListObjWarningsErrors {
            get {
                return ResourceManager.GetString("ListObjWarningsErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webpanels and Transactions called by Procedures.
        /// </summary>
        internal static string ListProcedureCallWebpanelTransaction {
            get {
                return ResourceManager.GetString("ListProcedureCallWebpanelTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List tables/attributes using domain.
        /// </summary>
        internal static string ListTableAttributesUsingDomain {
            get {
                return ResourceManager.GetString("ListTableAttributesUsingDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Tables.
        /// </summary>
        internal static string ListTables {
            get {
                return ResourceManager.GetString("ListTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List tables in modules.
        /// </summary>
        internal static string ListTablesInModules {
            get {
                return ResourceManager.GetString("ListTablesInModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables used by mains.
        /// </summary>
        internal static string MainTableUsed {
            get {
                return ResourceManager.GetString("MainTableUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Public Objects.
        /// </summary>
        internal static string MarkPublicObjects {
            get {
                return ResourceManager.GetString("MarkPublicObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules dependencies.
        /// </summary>
        internal static string ModuleDependencies {
            get {
                return ResourceManager.GetString("ModuleDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Transactions to Folders.
        /// </summary>
        internal static string MoveTransactions {
            get {
                return ResourceManager.GetString("MoveTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News without When Duplicate.
        /// </summary>
        internal static string NewsWithoutWhenDuplicate {
            get {
                return ResourceManager.GetString("NewsWithoutWhenDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex Specification Objects.
        /// </summary>
        internal static string ObjectsComplex {
            get {
                return ResourceManager.GetString("ObjectsComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects Diagnostics.
        /// </summary>
        internal static string ObjectsDiagnostics {
            get {
                return ResourceManager.GetString("ObjectsDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects with legacy code.
        /// </summary>
        internal static string ObjectsLegacyCode {
            get {
                return ResourceManager.GetString("ObjectsLegacyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mains called by others.
        /// </summary>
        internal static string ObjectsMainCalled {
            get {
                return ResourceManager.GetString("ObjectsMainCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove not referenced objects.
        /// </summary>
        internal static string ObjectsNotCalled {
            get {
                return ResourceManager.GetString("ObjectsNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark unreachable objects with GenerateObject=FALSE.
        /// </summary>
        internal static string ObjectsNotReacheable {
            get {
                return ResourceManager.GetString("ObjectsNotReacheable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate KBDoctor complexity index.
        /// </summary>
        internal static string ObjectsRefactoringCandidates {
            get {
                return ResourceManager.GetString("ObjectsRefactoringCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all object dependencies.
        /// </summary>
        internal static string ObjectsReferenced {
            get {
                return ResourceManager.GetString("ObjectsReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures that updates attributes.
        /// </summary>
        internal static string ObjectsUpdateAttribute {
            get {
                return ResourceManager.GetString("ObjectsUpdateAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated for WIN and WEB.
        /// </summary>
        internal static string ObjectsWINWEB {
            get {
                return ResourceManager.GetString("ObjectsWINWEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With parm() and Commit on exit=Yes.
        /// </summary>
        internal static string ObjectsWithCommitOnExit {
            get {
                return ResourceManager.GetString("ObjectsWithCommitOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects With Constants.
        /// </summary>
        internal static string ObjectsWithConstants {
            get {
                return ResourceManager.GetString("ObjectsWithConstants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With parm() without in:/out:/inout:.
        /// </summary>
        internal static string ObjectsWithoutInOut {
            get {
                return ResourceManager.GetString("ObjectsWithoutInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With variables not based on attribute/domain.
        /// </summary>
        internal static string ObjectsWithVarNotBasedOnAtt {
            get {
                return ResourceManager.GetString("ObjectsWithVarNotBasedOnAtt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects with variables not used.
        /// </summary>
        internal static string ObjectsWithVarsNotUsed {
            get {
                return ResourceManager.GetString("ObjectsWithVarsNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open navigation folder.
        /// </summary>
        internal static string OpenFolderComparerNavigation {
            get {
                return ResourceManager.GetString("OpenFolderComparerNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open object  in text format folder.
        /// </summary>
        internal static string OpenFolderObjComparerNavigation {
            get {
                return ResourceManager.GetString("OpenFolderObjComparerNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter type comparer.
        /// </summary>
        internal static string ParameterTypeComparer {
            get {
                return ResourceManager.GetString("ParameterTypeComparer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forced generation of SDT .
        /// </summary>
        internal static string PrcCalledByTrn {
            get {
                return ResourceManager.GetString("PrcCalledByTrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a snapshot of navigations.
        /// </summary>
        internal static string PrepareComparerNavigation {
            get {
                return ResourceManager.GetString("PrepareComparerNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Object by KBDoctor.
        /// </summary>
        internal static string PreprocessPendingObjects {
            get {
                return ResourceManager.GetString("PreprocessPendingObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Get/Set Procedures.
        /// </summary>
        internal static string ProcedureGetSet {
            get {
                return ResourceManager.GetString("ProcedureGetSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate SDT Sources.
        /// </summary>
        internal static string ProcedureSDT {
            get {
                return ResourceManager.GetString("ProcedureSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Module.
        /// </summary>
        internal static string RecomendedModule {
            get {
                return ResourceManager.GetString("RecomendedModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removable Transactions.
        /// </summary>
        internal static string RemovableTransactions {
            get {
                return ResourceManager.GetString("RemovableTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Objects to significant name length.
        /// </summary>
        internal static string RenameAttributesAndTables {
            get {
                return ResourceManager.GetString("RenameAttributesAndTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Domain.
        /// </summary>
        internal static string ReplaceDomain {
            get {
                return ResourceManager.GetString("ReplaceDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change attributes with Nullable=Compatible.
        /// </summary>
        internal static string ReplaceNullCompatible {
            get {
                return ResourceManager.GetString("ReplaceNullCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all transaction and workpanel WIN Forms.
        /// </summary>
        internal static string ResetWINForm {
            get {
                return ResourceManager.GetString("ResetWINForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Objects by KBDoctor.
        /// </summary>
        internal static string ReviewModuleOrFolder {
            get {
                return ResourceManager.GetString("ReviewModuleOrFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Object by KBDoctor.
        /// </summary>
        internal static string ReviewObject {
            get {
                return ResourceManager.GetString("ReviewObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Objects.
        /// </summary>
        internal static string ReviewObjects {
            get {
                return ResourceManager.GetString("ReviewObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search and Replace in Objects.
        /// </summary>
        internal static string SearchAndReplace {
            get {
                return ResourceManager.GetString("SearchAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;xsl:output method=&quot;text&quot;/&gt;
        ///
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;xsl:text&gt;Text Format Navigation for KBDoctor version 10.8&lt;/xsl:text&gt;
        ///    &lt;xsl:apply-templates select=&quot;ObjectSpec&quot;/&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;xsl:variable name=&quot;Product&quot; select=&quot;KBdoctor&quot;/&gt;
        ///  &lt;xsl:variable name=&quot;Images&quot;  select=&quot;Images&quot;/&gt;
        ///
        ///  &lt;xsl:template name=&quot;TableHeaderMain&quot;&gt;
        ///    &lt;xsl:param name=&quot;title&quot;&gt;Table Title&lt;/xsl:param&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string specXEv2 {
            get {
                return ResourceManager.GetString("specXEv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split main object.
        /// </summary>
        internal static string SplitMainObject {
            get {
                return ResourceManager.GetString("SplitMainObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New - Attribute not instanciated.
        /// </summary>
        internal static string TableInsertNew {
            get {
                return ResourceManager.GetString("TableInsertNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table&apos;s width.
        /// </summary>
        internal static string TablesWidth {
            get {
                return ResourceManager.GetString("TablesWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables with incomplete description.
        /// </summary>
        internal static string TablesWithNoDescription {
            get {
                return ResourceManager.GetString("TablesWithNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &lt;-&gt; Transaction Relation.
        /// </summary>
        internal static string TableTransaction {
            get {
                return ResourceManager.GetString("TableTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table - Update/Insert/Delete/Read.
        /// </summary>
        internal static string TableUpdate {
            get {
                return ResourceManager.GetString("TableUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree call - Commit.
        /// </summary>
        internal static string TreeCommit {
            get {
                return ResourceManager.GetString("TreeCommit", resourceCulture);
            }
        }
    }
}
