//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concepto.Packages.KBDoctor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Concepto.Packages.KBDoctor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;iso-8859-1&apos;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///
        ///
        ///&lt;!-- FORMULAS TEMPLATES --&gt;
        ///
        ///&lt;!-- AGGREGATE SELECT TEMPLATE --&gt;
        ///&lt;xsl:template match=&quot;AggSelFormulas&quot;&gt;
        ///	&lt;xsl:if test=&quot;Formula&quot;&gt;
        ///	-- Formulas:
        ///	&lt;xsl:for-each select=&quot;Formula&quot;&gt;
        ///	&lt;xsl:sort select=&quot;FormulaAttri/Attribute/AttriName&quot;/&gt;
        ///		&lt;xsl:choose&gt;
        ///			&lt;xsl:when test=&quot;FormulaType=&apos;aggsel&apos;&quot;&gt;
        ///		&lt;xsl:text&gt;Navigation to evaluate: &lt;/xsl:text &gt;&lt;xsl:apply-templates select=&quot;Formula [rest of string was truncated]&quot;;.
        /// </summary>
        public static string formulas {
            get {
                return ResourceManager.GetString("formulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;iso-8859-1&apos;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///
        ///
        ///&lt;!-- DYNAMIC COMBO NAVIGATION FOR TEXT FORMAT--&gt;
        ///&lt;xsl:template match=&quot;DynamicCombos&quot;&gt;
        ///	-- Dynamic Combos
        ///	&lt;xsl:for-each select=&quot;DynamicCombo&quot;&gt;
        ///	&lt;xsl:sort select=&quot;DynamicComboName&quot; order=&quot;ascending&quot;/&gt;
        ///		&lt;xsl:apply-templates select=&quot;.&quot;/&gt;
        ///	&lt;/xsl:for-each&gt;
        ///&lt;/xsl:template&gt;
        ///
        ///
        ///&lt;xsl:template match=&quot;DynamicCombo&quot;&gt;
        ///	Dynamic Combo Name: &lt;xsl:value-of select=&quot;DynamicComboName&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string genexusSpecific {
            get {
                return ResourceManager.GetString("genexusSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;iso-8859-1&apos;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///&lt;xsl:output method=&quot;html&quot; encoding=&quot;iso-8859-1&quot;/&gt;
        ///
        ///&lt;xsl:variable name=&quot;Product&quot; select=&quot;document(&apos;version.xml&apos;)/Product/Name&quot;/&gt;
        ///&lt;xsl:variable name=&quot;Images&quot;  select=&quot;document(&apos;images.xml&apos;)&quot;/&gt;
        ///
        ///&lt;xsl:template name=&quot;TableHeaderMain&quot;&gt;
        ///&lt;xsl:param name=&quot;title&quot;&gt;Table Title&lt;/xsl:param&gt;
        ///	---- &lt;xsl:value-of select=&quot;$title&quot;/&gt; ------
        ///&lt;/xsl:template&gt;
        ///
        ///&lt;xsl:template name=&quot;RelPathImage&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string include {
            get {
                return ResourceManager.GetString("include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  
        ///  &lt;xsl:output method=&quot;text&quot;/&gt;
        ///
        ///
        ///&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;xsl:text&gt;Text Format Navigation for GX X Evolution 1- Version 1.0&lt;/xsl:text&gt;
        ///	&lt;xsl:apply-templates select=&quot;ObjectSpec&quot;/&gt;
        ///&lt;/xsl:template&gt;
        ///
        ///&lt;xsl:include href=&quot;includeX.xsl&quot;/&gt;
        ///&lt;xsl:include href=&quot;formulas.xsl&quot;/&gt;
        ///&lt;xsl:include href=&quot;genexusSpecific90.xsl&quot;/&gt;
        ///
        ///
        ///
        ///&lt;!-- FROM FORMULA TEMPLATE --&gt;
        ///&lt;xsl:template match=&quot;FromFormula|FromValue&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string specXEv2 {
            get {
                return ResourceManager.GetString("specXEv2", resourceCulture);
            }
        }
    }
}
