using Artech.Architecture.Common.Collections;
using Artech.Architecture.Common.Objects;
using Artech.Architecture.Common.Services;
using Artech.Architecture.UI.Framework.Services;
using Artech.Genexus.Common.Helpers;
using Artech.Genexus.Common.Objects;
using Artech.Udm.Framework.References;
using Artech.Architecture.UI.Framework.Helper;
using Artech.Common.Framework.Commands;
using Artech.Genexus.Common.Entities;
using Artech.Genexus.Common;

using System;
using System.Collections.Generic;
using System.Text;

using Artech.Genexus.Common.Collections;
using System.Text.RegularExpressions;


using System.Linq;
using System.Xml;
using System.IO;

using System.Xml.Xsl;
using System.Diagnostics;
using System.Reflection;
using System.Resources;
using System.Collections;
using System.Threading;
using System.Globalization;
using Artech.Packages.Patterns.Definition;
using Artech.Packages.Patterns.Engine;
using Artech.Packages.Patterns;
using Artech.Packages.Patterns.Objects;
using Artech.Genexus.Common.Parts;
using Artech.Udm.Framework;
//using Artech.Genexus.Common.Resources;
using Concepto.Packages.KBDoctorCore.Sources;

namespace Concepto.Packages.KBDoctor
{
    static class KbStats
    {
        public static void CountGeneratedByPattern()
        {
            string title = "KBDoctor - Count objects generated by patterns";
            KBDoctorReport.Run(title, new string[] { "Name", "Type", "Description" }, writer =>
            {
                KbStatistics.GeneratedByPatternSummary summary = KbStatistics.CountGeneratedByPattern(UIServices.KB.CurrentModel);
                foreach (KbStatistics.BasicObjectInfo obj in summary.ObjectsNotGeneratedByPattern)
                {
                    writer.AddTableData(new string[] { Functions.linkObject(obj.Object), obj.Type, obj.Description });
                }

                writer.AddTableData(new string[] { " ", " ", " " });
                writer.AddTableData(new string[] { "Objects no generated with patterns / Total objects", summary.ObjectsNotGeneratedWithPatternsPercent + " %", "Obj.No Patterns=" + summary.ObjectsNotGeneratedWithPatterns + " Total Objects=" + summary.TotalObjects });
                Functions.AddLineSummary("SummaryPatternGeneration.txt", summary.SummaryText);
            });
        }

        public static void GeneratedByPatternWithoutDynamism()
        {
            string title = "KBDoctor - Generated by Patterns without Dynamism";
            KBDoctorReport.Run(title, new string[] { "Name", "Type", "Part", "Description" }, writer =>
            {
                int count = 0;
                foreach (KbStatistics.GeneratedPatternPartInfo part in KbStatistics.GetGeneratedPatternPartsWithoutDynamism(UIServices.KB.CurrentModel))
                {
                    KBDoctorOutput.Message(count + " " + part.Name + " " + part.PartName);
                    writer.AddTableData(new string[] { part.Name, part.Type, part.PartName, part.Description });
                    count++;
                }

                writer.AddTableData(new string[] { " Total ", count.ToString(), " ", "" });
            });
        }



        public static void ListObjDiffMasterPage2()
        {
            string title = "KBDoctor - Objects";
            KBDoctorReport.Run(title, new string[] { "Tipo", "Object", "Description", "Last Update", "Timestamp" }, writer =>
            {
                KBDoctorOutput.Message("Listing objects...");
                foreach (KbStatistics.BasicObjectInfo obj in KbStatistics.GetAllObjects(UIServices.KB.CurrentModel))
                {
                    writer.AddTableData(new string[] { obj.Type, obj.Name, obj.Description, obj.LastUpdate, obj.Timestamp });
                }
            });
        }

        public static void ListLastReports()
        {
            IKBService kbserv = UIServices.KB;

            Dictionary<string, KBObjectCollection> dic = new Dictionary<string, KBObjectCollection>();

            string title = "KBDoctor - List last Reports";
            try
            {
                string outputFile = Functions.CreateOutputFile(kbserv, title);

                IOutputService output = CommonServices.Output;
                KBDoctorOutput.StartSection(title);

                KBDoctorXMLWriter writer = new KBDoctorXMLWriter(outputFile, Encoding.UTF8);
                writer.AddHeader(title);

                writer.AddTableHeader(new string[] { "Report", "", "Date Generated" });

                string[] fileEntries = Directory.GetFiles(kbserv.CurrentKB.UserDirectory, "kbdoctor*.html");

                foreach (string fileName in fileEntries)
                {

                    string dateFilename = "";
                    int days = (int)(DateTime.Now - File.GetLastWriteTime(fileName)).TotalDays;
                    int hours = (int)(DateTime.Now - File.GetLastWriteTime(fileName)).TotalHours;
                    int mins = (int)(DateTime.Now - File.GetLastWriteTime(fileName)).TotalMinutes;

                    if (days > 0)
                        dateFilename = days.ToString() + " day(s) ago";
                    else
                        if (hours > 0)
                        dateFilename = hours.ToString() + " hour(s) ago";
                    else
                        dateFilename = mins.ToString() + " minutes(s) ago";

                    string shortFilename = Path.GetFileName(fileName);
                    shortFilename = shortFilename.Replace("kbdoctor.", "");
                    shortFilename = shortFilename.Replace(".html", "");
                    shortFilename = Regex.Replace(shortFilename, "(\\B[A-Z])", " $1");

                    string fileLink = "<a href=\"file:///" + fileName + "\">" + shortFilename + "</a>";
                    writer.AddTableData(new string[] { fileLink, dateFilename, File.GetLastWriteTime(fileName).ToString() });

                }
                writer.AddFooter();
                writer.Close();

                KBDoctorHelper.ShowKBDoctorResults(outputFile);
                bool success = true;
                KBDoctorOutput.EndSection(title, success);
            }
            catch
            {
                bool success = false;
                KBDoctor.KBDoctorOutput.EndSection(title, success);
            }
        }

        public static void ListObj()
        {
            string title = "KBDoctor - Objects";
            KBDoctorReport.Run(title, new string[] { "Type", "Object", "Description", "Module", "Public", "Last Update", "Is Main", "TimeStamp", "Is Generated", "Protocol", "QN" }, writer =>
            {
                foreach (KbStatistics.GeneratedObjectInfo obj in KbStatistics.GetGeneratedRunnableObjects(UIServices.KB.CurrentModel))
                {
                    writer.AddTableData(new string[] { obj.Type, Functions.linkObject(obj.Object), obj.Description, obj.ModuleName, obj.IsPublic, obj.LastUpdate, obj.IsMain, obj.Timestamp, obj.IsGenerated, obj.Protocol, obj.QualifiedName });
                }
            });
        }

        public static void ListUnreferencedObjectsInUserModules()
        {
            string title = "KBDoctor - Unreferenced objects in user modules";
            KBDoctorReport.Run(title, new string[] { "Type", "Object", "Description", "Module", "Public", "Last Update", "Action" }, writer =>
            {
                List<KbStatistics.UnreferencedUserModuleObjectInfo> objects = KbStatistics.GetUnreferencedObjectsInUserModules(UIServices.KB.CurrentModel).ToList();
                foreach (KbStatistics.UnreferencedUserModuleObjectInfo obj in objects)
                {
                    string action = obj.CanDelete ? Functions.CommandLink("RemoveObject", "Remove", "guid", obj.Object.Guid.ToString()) : string.Empty;
                    writer.AddTableData(new string[] { obj.Type, Functions.linkObject(obj.Object), obj.Description, obj.ModuleName, obj.IsPublic, obj.LastUpdate, action });
                }

                if (objects.Any(obj => obj.CanDelete))
                {
                    string removeAll = Functions.CommandLink("RemoveUnreferencedObjectsInUserModules", "<span style=\"display:inline-block;padding:6px 12px;background-color:#b00020;color:white;border-radius:3px;font-family:Tahoma;text-decoration:none;\">Remove all deletable objects</span>");
                    writer.WriteRaw("<tr><td colspan=\"7\" style=\"padding:10px;text-align:right;\">" + removeAll + "</td></tr>");
                }
            });
        }
        

        public static void ListMainObj()
        {
            string title = "KBDoctor - Main Objects";
            KBDoctorReport.Run(title, new string[] { "Type", "Object", "Description", "Module", "Public", "Generator", "Protocol", "Last Update" }, writer =>
            {
                foreach (KbStatistics.MainObjectInfo obj in KbStatistics.GetMainObjects(UIServices.KB.CurrentModel))
                {
                    writer.AddTableData(new string[] { obj.Type, Functions.linkObject(obj.Object), obj.Description, obj.ModuleName, obj.IsPublic, obj.AppGenerator, obj.Protocol, obj.LastUpdate });
                    KBDoctorOutput.Message(obj.Type + "," + obj.Object.Name + "," + obj.Object.Description);
                }
            });
        }


        public static void ListProc()
        {
            string title = "KBDoctor - Procedure";
            KBDoctorReport.Run(title, new string[] { "Type", "Object", "Commit ", "Module", "Public", "Generator", "Protocol", "Last Update" }, writer =>
            {
                foreach (KbStatistics.ProcedureInfo obj in KbStatistics.GetProcedures(UIServices.KB.CurrentModel, DateTime.Now))
                {
                    writer.AddTableData(new string[] { obj.Type, Functions.linkObject(obj.Object), obj.CommitOnExit, obj.ModuleName, obj.IsPublic, "", "", obj.LastUpdate });
                    KBDoctorOutput.Message(obj.Type + "," + obj.Object.Name + "," + obj.Object.Description);
                }
            });
        }



        public static void List2(KBObject obj, string objLocation, Dictionary<string, KBObjectCollection> dic,KBDoctorXMLWriter writer)
        {
            string objMasterPage = obj.GetPropertyValueString("MasterPage");
            writer.AddTableData(new string[] { obj.TypeDescriptor.Name, Functions.linkObject(obj), objLocation, objMasterPage });
            if (ObjectsHelper.IsCallalable(obj))
            {
                foreach (EntityReference reference in obj.GetReferences())
                {
                    KBObject objRef = KBObject.Get(obj.Model, reference.To);
                    string typeDescriptor = obj.TypeDescriptor.Name;
                    List<string> list = new List<string> { "WebPanel", "Transaction", "WorkPanel" };

                    if ((objRef != null) && list.Contains(typeDescriptor) && (reference.ReferenceType == ReferenceType.Hard))
                    {
                        int count = 0;
                        string locations = "";
                        KBObjectCollection objColl = new KBObjectCollection();
                        foreach (string loc in dic.Keys)
                        {
                            if ((loc != objLocation) && (list.Contains(objRef.TypeDescriptor.Name)))
                            {
                                dic.TryGetValue(loc, out objColl);
                                if (objColl.Contains(obj))
                                {
                                    locations += " " + loc;
                                    count += 1;
                                }
                            }
                        }
                        if (count > 0)
                        {
                            string objRefMasterPage = objRef.GetPropertyValueString("MasterPage");
                            writer.AddTableData(new string[] { "+-----Called >>" + objRef.TypeDescriptor.Name, Functions.linkObject(objRef), count.ToString() + "-" + locations, objRefMasterPage });
                        }
                    }
                }
            }

        }


        private static KBObjectCollection CreatLocationCollection(string location)
        {
            KBObjectCollection objColl = new KBObjectCollection();
            IKBService kB = UIServices.KB;
            IOutputService output = CommonServices.Output;
            KBCategory mainCategory = KBCategory.Get(kB.CurrentModel, "Main Programs");
            foreach (KBObject obj in Utility.EditableObjects(mainCategory.AllMembers))
            {
                string objLocation = (string)obj.GetProperty("AppLocation").Value;

                if (objLocation == "")
                    obj.SilentSetPropertyValue("AppLocation", "WEB");

                string objAppGenerator = obj.GetPropertyValueString("AppGenerator");
                string Dircopia;
                if (objAppGenerator.ToUpper().Contains("WEB"))
                    Dircopia = "Web\\bin\\";
                else
                    Dircopia = "bin\\";


                if (objLocation == null)
                    objLocation = "none";

                string letra = "";

                if (location == objLocation)
                {
                    KBDoctorOutput.Message("set DESTINO=" + objLocation);
                    KBDoctorOutput.Message("XCOPY " + Dircopia + obj.Name + ".dll %DESTINO%");

                    if (obj is Procedure)
                        letra = "a";
                    if (obj is WorkPanel)
                        letra = "u";
                    if (obj is Transaction)
                        letra = "";

                    KBDoctorOutput.Message("XCOPY " + Dircopia + letra + obj.Name + ".dll %DESTINO%");
                    AddReferencedObj(objColl, obj, "");

                }

            }
            return objColl;
        }

        private static void AddReferencedObj(KBObjectCollection objColl, KBObject obj, string tabs)
        {

            IKBService kbserv = UIServices.KB;
            IOutputService output = CommonServices.Output;
            objColl.Add(obj);
            string RefTabs = tabs + "    ";

            if (ObjectsHelper.IsCallalable(obj))
            {
                foreach (EntityReference reference in obj.GetReferences())
                {
                    KBObject objRef = KBObject.Get(obj.Model, reference.To);

                    if ((objRef != null) && !(objColl.Contains(objRef)) && (reference.ReferenceType == ReferenceType.Hard) && (ObjectsHelper.IsCallalable(objRef)))
                    {
                        if (!(objRef is Procedure))
                            KBDoctorOutput.Message(tabs + "XCOPY " + objRef.Name + ".DLL %DESTINO% "); //+ " (" + obj.TypeDescriptor.Name + ")" );

                        AddReferencedObj(objColl, objRef, RefTabs);

                    }
                }
            }
        }

        public static KBObject ObjectPartialName(string objName)
        {
            string[] ns = new[] { "Objects" };

            foreach (KBObject obj in UIServices.KB.CurrentModel.Objects.GetByPartialName(ns, objName))
            {
                if (obj.Name == objName)
                {

                    return obj;
                }

            }
            return null;
        }




        public static void ObjectsWINWEB()
        {
            IKBService kbserv = UIServices.KB;
            KBModel design = kbserv.CurrentModel;
      //      SpecificationListHelper helper = new SpecificationListHelper(design.Environment.TargetModel);


            string title = "KBDoctor - Objects called win y web";
            try
            {
                string outputFile = Functions.CreateOutputFile(kbserv, title);


                IOutputService output = CommonServices.Output;
                KBDoctorOutput.StartSection(title);


                KBDoctorXMLWriter writer = new KBDoctorXMLWriter(outputFile, Encoding.UTF8);
                writer.AddHeader(title);
                writer.AddTableHeader(new string[] { "Object", "Theme Object", "Component","Theme Component" });
                foreach (KBObject obj in Utility.EditableObjects(kbserv.CurrentModel.Objects.GetAll()))
                {

                    if (obj is WebPanel )
                    {
                        string objName = obj.Name;
                       // KBDoctorOutput.Message("Procesing down " + objName);

                        // Replace check of obj.IsComponent with property "WEB_COMP" == "Component"
                        string webComp = obj.GetPropertyValueString("WEB_COMP");
                        if (!string.IsNullOrEmpty(webComp) && webComp.Equals("Component", StringComparison.OrdinalIgnoreCase))
                        {
                            KBDoctorOutput.Message("Procesing up " + objName);


                            // 1) Store the Theme of the webcomponent
                            string compTheme = obj.GetPropertyValueString("Theme") ?? "";

                            // Write the component row so it's clear which theme is the reference
                            //writer.AddTableData(new string[] { Functions.linkObject(obj), compTheme, "WebComponent Theme" });

                            // 2) Iterate all incoming references to this webcomponent
                            foreach (EntityReference reference in obj.GetReferencesTo())
                            {
                                try
                                {
                                    KBObject fromObj = KBObject.Get(obj.Model, reference.From);
                                    if (fromObj == null)
                                        continue;

                                    // Read the referencing object's Theme
                                    string fromTheme = fromObj.GetPropertyValueString("Theme") ?? "";

                                    // If different (case-insensitive) list it
                                    if (!string.Equals(compTheme ?? string.Empty, fromTheme ?? string.Empty, StringComparison.OrdinalIgnoreCase))
                                    {
                                        string obs = string.IsNullOrEmpty(fromTheme) ? "Theme missing (component=" + compTheme + ")" : "Theme different (component=" + compTheme + ")";
                                        writer.AddTableData(new string[] { Functions.linkObject(fromObj), fromTheme, Functions.linkObject(obj), compTheme });
                                        KBDoctorOutput.Message($"Reference with different Theme: {fromObj.Name} (Theme='{fromTheme}') -> Component '{obj.Name}' (Theme='{compTheme}')");
                                    }
                                }
                                catch (Exception ex)
                                {
                                    // Avoid breaking the whole run on a single bad reference
                                    KBDoctorOutput.Message("Error processing reference to " + objName + ": " + ex.Message);
                                }
                            }
                        }
                    }
                }

                writer.AddFooter();
                writer.Close();

                KBDoctorHelper.ShowKBDoctorResults(outputFile);
                bool success = true;
                KBDoctorOutput.EndSection(title, success);
            }
            catch
            {
                bool success = false;
                KBDoctor.KBDoctorOutput.EndSection(title, success);
            }

        }

        private static IEnumerable<int> GetObjectGenerators(EntityKey key)
        {
            throw new NotImplementedException();
        }

        public static string MainsOf(KBObject obj, KBObjectCollection objColl, string callTree)
        {
            string mains = "";
            if (!objColl.Contains(obj))
            {
                objColl.Add(obj);

                if (obj.GetPropertyValue<bool>("IsMain"))
                {
                    string objAppGenerator = obj.GetPropertyValueString("AppGenerator");
                    if (objAppGenerator.Contains("Java Win") && callTree.Contains("HMaster"))
                    { mains = ""; }
                    else
                    { mains = callTree + "/" + Functions.linkObject(obj) + "(" + objAppGenerator + ")<BR> "; }

                }
                else
                {
                    callTree += obj.Name + "/";
                    foreach (EntityReference reference in obj.GetReferencesTo())
                    {
                        KBObject objRef = KBObject.Get(obj.Model, reference.From);

                        if ((objRef != null) && (obj.Name != objRef.Name) && (reference.ReferenceType == ReferenceType.Hard) && reference.LinkType == LinkType.UsedObject /*&& (obj.TypeDescriptor.Name != "MasterPage")*/ && !objColl.Contains(objRef))
                        {

                            mains += MainsOf(objRef, objColl, callTree);
                        }
                    }
                }
            }
            return mains;
        }

        public static void CompareLastNVGDirectory()
        {

            CompareLastDirectory("NVG");

        }

        public static void OpenFolderComparerNavigation()
        {

            Process.Start(KBDoctorHelper.NvgComparerDirectory(UIServices.KB));


        }

        public static void CompareLastOBJDirectory()
        {


            CompareLastDirectory("OBJ");
        }


        public static void OpenFolderObjComparerNavigation()
        {

            Process.Start(KBDoctorHelper.ObjComparerDirectory(UIServices.KB));

        }

        private static void CompareLastDirectory(string tipo)
        {

            string dirAppData = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "DiffDotNet");
            if (!File.Exists(Path.Combine(dirAppData, "DiffDotNet.exe")))
            {
                Directory.CreateDirectory(dirAppData);
                File.WriteAllBytes(Path.Combine(dirAppData, "MeneesDiffUtils.dll"), Comparer.MeneesDiffUtils);
                File.WriteAllBytes(Path.Combine(dirAppData, "Menees.dll"), Comparer.Menees);
                File.WriteAllBytes(Path.Combine(dirAppData, "DiffDotNet.exe"), Comparer.DiffDotNet);
            }

            // Start the child process.
            Process p = new Process();
            p.StartInfo.UseShellExecute = false;

            p.StartInfo.FileName = Path.Combine(dirAppData, "DiffDotNet.exe");

            //Saco directorio donde se guardan las comparaciones.
            IKBService kbserv = UIServices.KB;
            string dir = "";
            if (tipo == "NVG")
                    { dir = KBDoctorHelper.NvgComparerDirectory(kbserv); }
            if (tipo == "OBJ")
                    { dir = KBDoctorHelper.ObjComparerDirectory(kbserv); }

            string[] lastTwoDirectories = Utility.GetLastTwoComparerDirectories(dir, tipo);
            if (lastTwoDirectories.Length < 2)
            {
                string title = "KBDoctor - Compare files";
                IOutputService output = CommonServices.Output;
                KBDoctorOutput.StartSection(title);
                KBDoctorOutput.Error("There isn't two directory to compare in " + dir + ". You must generate files first and then compare ");
                KBDoctorOutput.EndSection(title, true);

            }
            else
            {
                string newestDirectory = lastTwoDirectories[0];
                string previousDirectory = lastTwoDirectories[1];
                p.StartInfo.Arguments = QuoteProcessArgument(previousDirectory) + " " + QuoteProcessArgument(newestDirectory);
                p.Start();
            }
        }

        private static string QuoteProcessArgument(string argument)
        {
            if (argument == null)
            {
                return "\"\"";
            }

            return "\"" + argument.Replace("\"", "\\\"") + "\"";
        }

        public static void KBInterfaces()
        {
            IKBService kbserv = UIServices.KB;
            KBModel design = kbserv.CurrentModel;
            SpecificationListHelper helper = new SpecificationListHelper(design.Environment.TargetModel);

            string outputFile = kbserv.CurrentKB.UserDirectory + @"\kbdoctor.KBInterfaces.html";
            if (File.Exists(outputFile))
            {
                File.Delete(outputFile);
            }

            string titulo = "KBDoctor - KB Interfaces";
            IOutputService output = CommonServices.Output;
            KBDoctorOutput.StartSection(titulo);


           KBDoctorXMLWriter writer = new KBDoctorXMLWriter(outputFile, Encoding.UTF8);
            writer.AddHeader(titulo);
            writer.AddTableHeader(new string[] {"Type", "Object", "Variable", "Type", "Module" });

            foreach (KBObject obj in Utility.EditableObjects(kbserv.CurrentModel.Objects.GetAll()))
            {

                if (obj != null)
                {
                    KBDoctorOutput.Message("Procesing  " + obj.Name);

                 //   IEnumerable<int> generatorTypes = KbStats.GetObjectGenerators(obj.Key);

                    KBObjectCollection objColl = new KBObjectCollection();
                    string tipo = "";

                    string mainss = "";


                    foreach (EntityReference reference in obj.GetReferences())
                    {
                        KBObject objRef = KBObject.Get(obj.Model, reference.To);

                        if (objRef != null)
                        {
                            if (objRef is ExternalObject)
                            {
                                tipo = "External Object:" + objRef.GetPropertyValueString("ExoType");
                                writer.AddTableData(new string[] { obj.TypeDescriptor.Name, Functions.linkObject(obj), Functions.linkObject(objRef), tipo, obj.Module.Name });
                            }
                            else
                            {
                                if (objRef is MissingKBObject)
                                {
                                    tipo = "Missing Object";
                                    writer.AddTableData(new string[] { obj.TypeDescriptor.Name, Functions.linkObject(obj), Functions.linkObject(objRef), tipo, obj.Module.Name });
                                }
                            }

                        }




                    }


                    string sourceWOComments = Functions.ExtractComments(Functions.ObjectSourceUpper(obj));

                    sourceWOComments = sourceWOComments.Replace("\t", " ");

                    AddLineKBInterfazSource(writer, obj, "SHELL ", "CMD.", sourceWOComments, obj.Module.Name);
                    AddLineKBInterfazSource(writer, obj, "JAVA ", "CMD.", sourceWOComments, obj.Module.Name);
                    AddLineKBInterfazSource(writer, obj, "CSHARP ", "CMD.", sourceWOComments, obj.Module.Name);
                    AddLineKBInterfazSource(writer, obj, "SQL ", "CMD.", sourceWOComments, obj.Module.Name);


                    ObjectsVariablesExternal(obj, writer, mainss);
                    if (obj is Transaction || obj is WebPanel)
                        UserControlUsageCheck(obj, writer, mainss);

                }
            }

            writer.AddFooter();
            writer.Close();

            KBDoctorHelper.ShowKBDoctorResults(outputFile);
            bool success = true;
            KBDoctorOutput.EndSection(titulo, success);

        }

        private static void AddLineKBInterfazSource( KBDoctorXMLWriter writer, KBObject obj, string texto, string tipo, string sourceWOComments, string mainss)
        {

            KBObjectCollection objColl = new KBObjectCollection();

            if (sourceWOComments.Contains(texto))
            {
                writer.AddTableData(new string[] { obj.TypeDescriptor.Name, Functions.linkObject(obj), "", "CMD." + texto, obj.Module.Name });
            }

        }

        public static void ObjectsVariablesExternal(KBObject obj,KBDoctorXMLWriter writer, string mainss)
        {
            IKBService kbserv = UIServices.KB;

            string type = "";
            string name = "";
            string variables = "";


            if (KBDoctorCore.Sources.Utility.isGenerated(obj))
            {
                VariablesPart vp = obj.Parts.Get<VariablesPart>();
                if (vp != null)
                {
                    foreach (Variable v in vp.Variables)
                    {
                        type = v.Type.ToString();
                        name = v.Name;

                        if ((!v.IsStandard) && (v.AttributeBasedOn == null) && (type == "GX_USRDEFTYP")) //|| (type==) || (type == "GX_BUSCOMP_LEVEL") )
                        {
                            variables += name + " " + type + " ";
                            string txtDimensions = v.GetPropertyValue<string>(Properties.ATT.DataTypeString);
                            writer.AddTableData(new string[] { obj.TypeDescriptor.Name, Functions.linkObject(obj), name, "Data Type." + txtDimensions, obj.Module.Name });

                        }


                    }

                }

            }




        }


        public static void UserControlUsageCheck(KBObject obj,KBDoctorXMLWriter writer, string mainss)
        {

            Artech.Genexus.Common.Parts.WebFormPart webpart = obj.Parts.Get<Artech.Genexus.Common.Parts.WebFormPart>();

            if (webpart != null)
            {
                foreach (Artech.Genexus.Common.Parts.WebForm.IWebTag tag in Artech.Genexus.Common.Parts.WebForm.WebFormHelper.EnumerateWebTag(webpart))
                {
                    if (tag.IsUserControl)
                    {
                        string ucType = tag.Properties.GetPropertyValueString("UserControlType");
                        string ctrlName = tag.Properties.GetPropertyValueString("ControlName");
                        writer.AddTableData(new string[] { obj.TypeDescriptor.Name, Functions.linkObject(obj), ctrlName, "UC." + ucType, mainss });
                    }
                }
            }
        }




    }
}
