using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml;
using Artech.Architecture.Common.Descriptors;
using Artech.Architecture.Common.Objects;
using Artech.Architecture.Common.Services;
using Artech.Architecture.UI.Framework.Services;
using Artech.Genexus.Common;
using Artech.Genexus.Common.CustomTypes;
using Artech.Genexus.Common.Objects;
using Artech.Genexus.Common.Parts;
using Artech.Genexus.Common.Parts.WebForm;
using Concepto.Packages.KBDoctorCore.Sources;

namespace Concepto.Packages.KBDoctor
{
    static class ResponsiveSmoothActions
    {
        public static void Run(string action)
        {
            string title = "KBDoctor - Responsive/Smooth actions";
            KBDoctorOutput.StartSection(title);
            switch (action)
            {
                case "responsiveDefaults":
                    ConvertDefaultResponsiveProperties();
                    break;
                case "smoothDefaults":
                    ConvertDefaultWebUXToSmooth();
                    break;
                case "generatedPreviousToSmooth":
                    ConvertGeneratedPreviousCompatibleToSmooth();
                    break;
                case "auditSmoothResponsive":
                    AuditSmoothResponsive();
                    break;
                case "resetDefaultMasterPage":
                    ResetDefaultMasterPageReferences();
                    break;
                case "webFormToAbstractEditor":
                    WebFormToAbstractEditor();
                    break;
                case "improveControlClasses":
                    UIFrontendActions.ImproveControlClasses();
                    break;
                case "auditWebPanelsSmoothUX":
                    AnalyzeWebPanelsSmoothUX(false);
                    break;
                case "convertSafeWebPanelsToSmoothUX":
                    AnalyzeWebPanelsSmoothUX(true);
                    break;
                default:
                    KBDoctorOutput.Error("Unknown action: " + action);
                    KBDoctorOutput.EndSection(title, false);
                    return;
            }

            KBDoctorOutput.EndSection(title, true);
        }

        private static void WebFormToAbstractEditor()
        {
            KBModel kbModel = UIServices.KB.CurrentModel;
            IOutputService output = CommonServices.Output;
            SelectObjectOptions selectObjectOption = new SelectObjectOptions();
            selectObjectOption.MultipleSelection = true;
            selectObjectOption.ObjectTypes.Add(KBObjectDescriptor.Get<WebPanel>());

            int selected = 0;
            int changed = 0;
            int alreadyAbstract = 0;
            int converted = 0;
            int notConverted = 0;
            int skippedPattern = 0;
            int failed = 0;
            int reportRows = 0;
            string reportTitle = "KBDoctor - WebForm to Abstract Editor";
            string outputFile = Functions.CreateOutputFile(UIServices.KB, reportTitle);
            KBDoctorXMLWriter writer = new KBDoctorXMLWriter(outputFile, Encoding.UTF8);
            writer.AddHeader(reportTitle);
            writer.AddTableHeader(new string[] { "Name", "Module", "MasterPage", "Style", "TypeEditor", "Conversion Result" });
            Dictionary<string, string> classReplacements = LoadClassReplacements();
            List<WebPanel> webPanels = UIServices.SelectObjectDialog.SelectObjects(selectObjectOption).Cast<WebPanel>().ToList();
            int total = webPanels.Count;

            output.AddLine("Object,MasterPage Default,Style Default,Was Abstract,Is Abstract,Result");

            foreach (WebPanel webPanel in webPanels)
            {
                selected += 1;
                string progress = "(" + selected.ToString() + "/" + total.ToString() + ") ";
                output.AddLine(progress + "Processing " + webPanel.Name);

                if (ObjectsHelper.isGeneratedbyPattern(webPanel))
                {
                    skippedPattern += 1;
                    bool patternIsAbstract = SafeWebPanelFormRootIsAbstract(webPanel.WebForm);
                    writer.AddTableData(new[]
                    {
                        Functions.linkObject(webPanel),
                        Html(webPanel.Module == null ? "" : webPanel.Module.Name),
                        Html(SafeGetPropertyValueString(webPanel, Properties.TRN.MasterPage)),
                        Html(SafeGetPropertyValueString(webPanel, Properties.TRN.Theme)),
                        Html((patternIsAbstract ? "Abstract Layout" : "HTML") + " -> " + (patternIsAbstract ? "Abstract Layout" : "HTML")),
                        Html("Skipped: object generated by pattern. No properties or editor changes were applied.")
                    });
                    reportRows += 1;
                    output.AddLine(progress + webPanel.Name + ",False,False," + patternIsAbstract.ToString() + "," + patternIsAbstract.ToString() + ",Skipped: object generated by pattern");
                    continue;
                }

                if (!Utility.IsUserEditableObject(webPanel))
                {
                    failed += 1;
                    bool readOnlyIsAbstract = SafeWebPanelFormRootIsAbstract(webPanel.WebForm);
                    writer.AddTableData(new[]
                    {
                        Functions.linkObject(webPanel),
                        Html(webPanel.Module == null ? "" : webPanel.Module.Name),
                        Html(SafeGetPropertyValueString(webPanel, Properties.TRN.MasterPage)),
                        Html(SafeGetPropertyValueString(webPanel, Properties.TRN.Theme)),
                        Html((readOnlyIsAbstract ? "Abstract Layout" : "HTML") + " -> " + (readOnlyIsAbstract ? "Abstract Layout" : "HTML")),
                        Html("Error: Read-only object")
                    });
                    reportRows += 1;
                    output.AddLine(progress + webPanel.Name + ",False,False,False,False,Read-only object");
                    continue;
                }

                bool wasAbstract = SafeWebPanelFormRootIsAbstract(webPanel.WebForm);
                string masterPageBefore = SafeGetPropertyValueString(webPanel, Properties.TRN.MasterPage);
                string styleBefore = SafeGetPropertyValueString(webPanel, Properties.TRN.Theme);
                bool masterPageDefault = ResetPropertyToDefault(webPanel, Properties.TRN.MasterPage);
                bool styleDefault = ResetPropertyToDefault(webPanel, Properties.TRN.Theme);
                bool conversionChanged = false;
                string conversionMessage;

                try
                {
                    conversionChanged = TryConvertWebFormToAbstract(webPanel, classReplacements, out conversionMessage);
                    bool isAbstractAfterConversion = SafeWebPanelFormRootIsAbstract(webPanel.WebForm);
                    if (!wasAbstract && !isAbstractAfterConversion)
                    {
                        failed += 1;
                        string failedResult = "Error: Conversion failed. Object was not saved. " + conversionMessage;
                        writer.AddTableData(new[]
                        {
                            Functions.linkObject(webPanel),
                            Html(webPanel.Module == null ? "" : webPanel.Module.Name),
                            Html(masterPageBefore),
                            Html(styleBefore),
                            Html("HTML -> HTML"),
                            Html(failedResult)
                        });
                        reportRows += 1;
                        output.AddLine(progress + webPanel.Name + "," + masterPageDefault.ToString() + "," + styleDefault.ToString() + "," + wasAbstract.ToString() + ",False," + failedResult);
                        continue;
                    }

                    webPanel.Save();
                    changed += 1;
                }
                catch (Exception e)
                {
                    failed += 1;
                    output.AddErrorLine("WebForm to Abstract Editor failed for " + webPanel.Name + ": " + e.ToString());
                    writer.AddTableData(new[]
                    {
                        Functions.linkObject(webPanel),
                        Html(webPanel.Module == null ? "" : webPanel.Module.Name),
                        Html(masterPageBefore),
                        Html(styleBefore),
                        Html((wasAbstract ? "Abstract Layout" : "HTML") + " -> " + (wasAbstract ? "Abstract Layout" : "HTML")),
                        Html("Error: Conversion/save failed. No additional save was attempted: " + e.Message)
                    });
                    reportRows += 1;
                    output.AddLine(progress + webPanel.Name + "," + masterPageDefault.ToString() + "," + styleDefault.ToString() + "," + wasAbstract.ToString() + "," + wasAbstract.ToString() + ",Conversion/save failed. No additional save was attempted: " + e.Message);
                    continue;
                }

                bool isAbstract = SafeWebPanelFormRootIsAbstract(webPanel.WebForm);
                string result;
                if (wasAbstract)
                {
                    alreadyAbstract += 1;
                    result = "Already abstract";
                }
                else if (conversionChanged && isAbstract)
                {
                    converted += 1;
                    result = "Converted to abstract editor. " + conversionMessage;
                }
                else if (isAbstract)
                {
                    converted += 1;
                    result = "Converted to abstract editor by save/defaults. " + conversionMessage;
                }
                else
                {
                    notConverted += 1;
                    result = "Still old HTML editor. " + conversionMessage;
                }

                string masterPageAfter = SafeGetPropertyValueString(webPanel, Properties.TRN.MasterPage);
                string styleAfter = SafeGetPropertyValueString(webPanel, Properties.TRN.Theme);
                bool objectChanged = conversionChanged
                    || wasAbstract != isAbstract
                    || !string.Equals(masterPageBefore, masterPageAfter, StringComparison.Ordinal)
                    || !string.Equals(styleBefore, styleAfter, StringComparison.Ordinal);

                if (objectChanged)
                {
                    writer.AddTableData(new[]
                    {
                        Functions.linkObject(webPanel),
                        Html(webPanel.Module == null ? "" : webPanel.Module.Name),
                        Html(masterPageAfter),
                        Html(styleAfter),
                        Html((wasAbstract ? "Abstract Layout" : "HTML") + " -> " + (isAbstract ? "Abstract Layout" : "HTML")),
                        Html(result)
                    });
                    reportRows += 1;
                }

                output.AddLine(progress + webPanel.Name + "," + masterPageDefault.ToString() + "," + styleDefault.ToString() + "," + wasAbstract.ToString() + "," + isAbstract.ToString() + "," + result);
            }

            writer.AddFooter();
            writer.Close();
            output.AddLine("Report rows: " + reportRows.ToString());
            output.AddLine("Report: " + outputFile);
            KBDoctorHelper.ShowKBDoctorResults(outputFile);
            if (reportRows > 0)
            {
                output.AddLine("Report includes WebPanels changed or with conversion errors.");
            }
            else
            {
                output.AddLine("No WebPanels changed. Report was generated without rows: " + outputFile);
            }

            output.AddLine("");
            output.AddLine("Selected: " + selected.ToString()
                + ". Saved: " + changed.ToString()
                + ". Already abstract: " + alreadyAbstract.ToString()
                + ". Converted: " + converted.ToString()
                + ". Still old HTML editor: " + notConverted.ToString()
                + ". Skipped pattern generated: " + skippedPattern.ToString()
                + ". Failed: " + failed.ToString() + ".");
        }

        private static void AnalyzeWebPanelsSmoothUX(bool convertSafeOnly)
        {
            IOutputService output = CommonServices.Output;
            SelectObjectOptions selectObjectOption = new SelectObjectOptions();
            selectObjectOption.MultipleSelection = true;
            selectObjectOption.ObjectTypes.Add(KBObjectDescriptor.Get<WebPanel>());

            string reportTitle = convertSafeOnly
                ? "KBDoctor - Convert safe WebPanels to Smooth UX"
                : "KBDoctor - Audit WebPanels Smooth UX";
            string outputFile = Functions.CreateOutputFile(UIServices.KB, reportTitle);
            KBDoctorXMLWriter writer = new KBDoctorXMLWriter(outputFile, Encoding.UTF8);
            writer.AddHeader(reportTitle);
            writer.AddTableHeader(new[]
            {
                "Object",
                "Module",
                "WebUX",
                "ProposedWebUX",
                "AutomaticRefresh",
                "MasterPage",
                "Style",
                "TypeEditor",
                "Events",
                "WebComponents",
                "Risk",
                "Reason",
                "Action"
            });

            output.AddLine("Object,Module,WebUX,ProposedWebUX,AutomaticRefresh,MasterPage,Style,TypeEditor,Events,WebComponents,Risk,Reason,Action");

            int selected = 0;
            int safe = 0;
            int review = 0;
            int alreadySmooth = 0;
            int changed = 0;
            int failed = 0;

            foreach (WebPanel webPanel in UIServices.SelectObjectDialog.SelectObjects(selectObjectOption))
            {
                selected += 1;
                SmoothUxAnalysis analysis = AnalyzeWebPanelSmoothUX(webPanel);

                if (analysis.AlreadySmooth)
                {
                    alreadySmooth += 1;
                }
                else if (analysis.SafeToConvert)
                {
                    safe += 1;
                }
                else
                {
                    review += 1;
                }

                if (convertSafeOnly && analysis.SafeToConvert)
                {
                    try
                    {
                        ApplySmoothUxConversion(analysis);
                        changed += 1;
                    }
                    catch (Exception e)
                    {
                        failed += 1;
                        analysis.Risk = "Failed";
                        analysis.Action = "Save failed: " + e.Message;
                        output.AddErrorLine("Smooth UX conversion failed for " + webPanel.Name + ": " + e.ToString());
                    }
                }

                writer.AddTableData(new[]
                {
                    Functions.linkObject(webPanel),
                    Html(analysis.Module),
                    Html(analysis.CurrentWebUX),
                    Html(analysis.ProposedWebUX),
                    Html(analysis.AutomaticRefresh),
                    Html(analysis.MasterPage),
                    Html(analysis.Style),
                    Html(analysis.TypeEditor),
                    Html(analysis.Events),
                    Html(analysis.WebComponents),
                    Html(analysis.Risk),
                    Html(analysis.Reason),
                    Html(analysis.Action)
                });

                output.AddLine(webPanel.Name
                    + "," + analysis.Module
                    + "," + analysis.CurrentWebUX
                    + "," + analysis.ProposedWebUX
                    + "," + analysis.AutomaticRefresh
                    + "," + analysis.MasterPage
                    + "," + analysis.Style
                    + "," + analysis.TypeEditor
                    + "," + analysis.Events
                    + "," + analysis.WebComponents
                    + "," + analysis.Risk
                    + "," + analysis.Reason
                    + "," + analysis.Action);
            }

            writer.AddFooter();
            writer.Close();
            output.AddLine("");
            output.AddLine("Selected: " + selected.ToString()
                + ". Already Smooth: " + alreadySmooth.ToString()
                + ". Safe to convert: " + safe.ToString()
                + ". Needs review: " + review.ToString()
                + ". Changed: " + changed.ToString()
                + ". Failed: " + failed.ToString() + ".");
            output.AddLine("Report: " + outputFile);
            KBDoctorHelper.ShowKBDoctorResults(outputFile);
        }

        private static SmoothUxAnalysis AnalyzeWebPanelSmoothUX(WebPanel webPanel)
        {
            SmoothUxAnalysis analysis = new SmoothUxAnalysis();
            analysis.WebPanel = webPanel;
            analysis.Module = webPanel.Module == null ? "" : webPanel.Module.Name;
            analysis.CurrentWebUX = SafeGetPropertyValueString(webPanel, Properties.TRN.WebUserExperience);
            analysis.ProposedWebUX = Properties.TRN.WebUserExperience_Values.Smooth;
            analysis.MasterPage = SafeGetPropertyValueString(webPanel, Properties.TRN.MasterPage);
            analysis.Style = SafeGetPropertyValueString(webPanel, Properties.TRN.Theme);
            analysis.TypeEditor = SafeWebPanelFormRootIsAbstract(webPanel.WebForm) ? "Abstract Layout" : "HTML";
            analysis.AutomaticRefresh = DescribeAutomaticRefresh(webPanel);
            analysis.Events = DescribeEvents(webPanel, out bool hasUserEvents, out bool hasExplicitRefresh, out bool hasStartSecurityRisk);
            analysis.WebComponents = DescribeWebComponents(webPanel.WebForm, out bool hasWebComponents);
            analysis.AlreadySmooth = string.Equals(analysis.CurrentWebUX, "Smooth", StringComparison.OrdinalIgnoreCase);

            List<string> reasons = new List<string>();
            if (!Utility.IsUserEditableObject(webPanel))
            {
                reasons.Add("Read-only object");
            }

            if (ObjectsHelper.isGenerated(webPanel) || ObjectsHelper.isGeneratedbyPattern(webPanel))
            {
                reasons.Add("Generated or pattern object");
            }

            if (analysis.AlreadySmooth)
            {
                reasons.Add("Already Smooth");
            }

            if (hasWebComponents)
            {
                reasons.Add("Contains Web Components; component UX must be reviewed");
            }

            if (hasUserEvents)
            {
                reasons.Add(hasExplicitRefresh
                    ? "Contains user events; review refresh behavior"
                    : "Contains user events without explicit Refresh");
            }

            if (hasStartSecurityRisk)
            {
                reasons.Add("Start event has security/session checks");
            }

            if (analysis.TypeEditor == "HTML")
            {
                reasons.Add("Old HTML editor; convert to abstract editor first");
            }

            analysis.SafeToConvert = reasons.Count == 0;
            analysis.Risk = analysis.SafeToConvert ? "Safe to convert" : (analysis.AlreadySmooth ? "Already Smooth" : "Needs review");
            analysis.Reason = reasons.Count == 0 ? "No Smooth UX risk markers found" : string.Join("; ", reasons.ToArray());
            analysis.Action = analysis.SafeToConvert ? "Pending conversion" : "No changes";
            return analysis;
        }

        private static void ApplySmoothUxConversion(SmoothUxAnalysis analysis)
        {
            WebPanel webPanel = analysis.WebPanel;
            string beforeAutoRefresh = analysis.AutomaticRefresh;
            webPanel.SetPropertyValue(Properties.TRN.WebUserExperience, Properties.TRN.WebUserExperience_Values.Smooth);
            bool autoRefreshChanged = SetAutomaticRefreshToNo(webPanel);
            webPanel.Save();

            analysis.CurrentWebUX = SafeGetPropertyValueString(webPanel, Properties.TRN.WebUserExperience);
            analysis.AutomaticRefresh = DescribeAutomaticRefresh(webPanel);
            analysis.Risk = "Converted";
            analysis.Action = autoRefreshChanged
                ? "Web UX set to Smooth; Automatic Refresh changed from " + beforeAutoRefresh + " to " + analysis.AutomaticRefresh
                : "Web UX set to Smooth";
        }

        private static string DescribeEvents(WebPanel webPanel, out bool hasUserEvents, out bool hasExplicitRefresh, out bool hasStartSecurityRisk)
        {
            hasUserEvents = false;
            hasExplicitRefresh = false;
            hasStartSecurityRisk = false;
            EventsPart eventsPart = webPanel.Parts.Get<EventsPart>();
            string source = eventsPart == null ? "" : eventsPart.Source;
            string sourceWithoutComments = Utility.ExtractComments(source ?? "");
            List<string> events = new List<string>();

            foreach (Match match in Regex.Matches(sourceWithoutComments, @"(?im)^\s*Event\s+(.+?)\s*$"))
            {
                string eventName = match.Groups[1].Value.Trim().Trim('\'', '"');
                string normalized = eventName.ToUpperInvariant();
                events.Add(eventName);
                if (normalized != "START" && normalized != "REFRESH" && normalized != "LOAD")
                {
                    hasUserEvents = true;
                }
            }

            hasExplicitRefresh = Regex.IsMatch(sourceWithoutComments, @"(?im)\bRefresh\b|\bForm\.Refresh\b|\.Refresh\s*\(");
            Match startMatch = Regex.Match(sourceWithoutComments, @"(?is)\bEvent\s+Start\b(?<body>.*?)(?=\bEvent\s+|$)");
            if (startMatch.Success)
            {
                string body = startMatch.Groups["body"].Value;
                hasStartSecurityRisk = Regex.IsMatch(body, @"(?i)\b(GAM|Security|Permission|Authorized|IsAuthorized|Session|Login|Logout|User)\b");
            }

            return events.Count == 0 ? "No events" : string.Join(" | ", events.ToArray());
        }

        private static string DescribeWebComponents(WebFormPart webForm, out bool hasWebComponents)
        {
            hasWebComponents = false;
            if (webForm == null || string.IsNullOrEmpty(webForm.EditableContent))
            {
                return "No explicit WebForm";
            }

            string xml = webForm.EditableContent;
            hasWebComponents = Regex.IsMatch(xml, @"(?i)webcomponent|gxwebcomponent");
            if (!hasWebComponents)
            {
                return "No";
            }

            List<string> componentNames = new List<string>();
            foreach (Match match in Regex.Matches(xml, @"(?i)(?:Object|Name|ControlName)=""([^""]+)"""))
            {
                string value = match.Groups[1].Value;
                if (!string.IsNullOrEmpty(value) && componentNames.Count < 8 && !componentNames.Contains(value))
                {
                    componentNames.Add(value);
                }
            }

            return componentNames.Count == 0 ? "Yes" : string.Join(" | ", componentNames.ToArray());
        }

        private static string DescribeAutomaticRefresh(WebPanel webPanel)
        {
            string objectValue = SafeGetPropertyValueString(webPanel, Properties.WBP.AutomaticRefresh);
            WebFormPart webForm = webPanel.WebForm;
            if (webForm == null || string.IsNullOrEmpty(webForm.EditableContent))
            {
                return string.IsNullOrEmpty(objectValue) ? "No explicit WebForm" : objectValue;
            }

            List<string> values = new List<string>();
            foreach (Match match in Regex.Matches(webForm.EditableContent, @"\bREFRESH=""([^""]+)""", RegexOptions.IgnoreCase))
            {
                string value = match.Groups[1].Value;
                if (!values.Contains(value))
                {
                    values.Add(value);
                }
            }

            if (values.Count == 0)
            {
                return string.IsNullOrEmpty(objectValue) ? "Default" : objectValue;
            }

            string formValues = string.Join(" | ", values.ToArray());
            return string.IsNullOrEmpty(objectValue) ? formValues : objectValue + " (Form: " + formValues + ")";
        }

        private static bool SetAutomaticRefreshToNo(WebPanel webPanel)
        {
            bool changed = false;
            if (webPanel.ContainsPropertyDefinition(Properties.WBP.AutomaticRefresh)
                && !string.Equals(webPanel.GetPropertyValueString(Properties.WBP.AutomaticRefresh), Properties.WBP.AutomaticRefresh_Values.No, StringComparison.OrdinalIgnoreCase))
            {
                webPanel.SetPropertyValue(Properties.WBP.AutomaticRefresh, Properties.WBP.AutomaticRefresh_Values.No);
                changed = true;
            }

            WebFormPart webForm = webPanel.WebForm;
            if (webForm == null || string.IsNullOrEmpty(webForm.EditableContent))
            {
                return changed;
            }

            string newContent = Regex.Replace(webForm.EditableContent, @"\bREFRESH=""ALL""", "REFRESH=\"COND\"", RegexOptions.IgnoreCase);
            if (!string.Equals(newContent, webForm.EditableContent, StringComparison.Ordinal))
            {
                webForm.EditableContent = newContent;
                changed = true;
            }

            return changed;
        }

        private static bool SafeWebPanelFormRootIsAbstract(WebFormPart part)
        {
            try
            {
                return WebPanelFormRootIsAbstract(part);
            }
            catch
            {
                return false;
            }
        }

        private class SmoothUxAnalysis
        {
            public WebPanel WebPanel { get; set; }
            public string Module { get; set; }
            public string CurrentWebUX { get; set; }
            public string ProposedWebUX { get; set; }
            public string AutomaticRefresh { get; set; }
            public string MasterPage { get; set; }
            public string Style { get; set; }
            public string TypeEditor { get; set; }
            public string Events { get; set; }
            public string WebComponents { get; set; }
            public string Risk { get; set; }
            public string Reason { get; set; }
            public string Action { get; set; }
            public bool SafeToConvert { get; set; }
            public bool AlreadySmooth { get; set; }
        }

        private static string SafeGetPropertyValueString(KBObject obj, string propertyName)
        {
            if (!obj.ContainsPropertyDefinition(propertyName))
            {
                return "";
            }

            return obj.GetPropertyValueString(propertyName);
        }

        private static string Html(string text)
        {
            return SecurityElement.Escape(text ?? "");
        }

        private static bool ResetPropertyToDefault(KBObject obj, string propertyName)
        {
            if (!obj.ContainsPropertyDefinition(propertyName))
            {
                return false;
            }

            if (!obj.IsPropertyDefault(propertyName) && obj.CanResetValue(propertyName))
            {
                obj.ResetProperty(propertyName);
            }

            return obj.IsPropertyDefault(propertyName);
        }

        private static bool TryConvertWebFormToAbstract(WebPanel webPanel, Dictionary<string, string> classReplacements, out string message)
        {
            message = "";
            WebFormPart webForm = webPanel.WebForm;
            if (webForm == null || string.IsNullOrEmpty(webForm.EditableContent))
            {
                message = "No explicit WebForm content";
                return false;
            }

            XmlDocument formDocument = new XmlDocument();
            string originalEditableContent = webForm.EditableContent;
            formDocument.LoadXml(webForm.EditableContent);
            bool resolvedStoredReferences = ResolveStoredReferencesBeforeLayoutConversion(webPanel, formDocument);
            string editableXmlBeforeConversion = formDocument.OuterXml;

            int rootFormId = MultiFormSerializer.GetRootFormId(formDocument);
            List<MultiFormSerializer.Form> forms = MultiFormSerializer.GetForms(formDocument).ToList();
            MultiFormSerializer.Form rootForm = forms.FirstOrDefault(form => form.Id == rootFormId);
            if (rootForm == null)
            {
                message = "Root form not found";
                return false;
            }

            if (rootForm.Handler.XmlTypeName == MultiForm.Layout.XmlTypeName)
            {
                message = "Root form is already layout";
                return false;
            }

            if (rootForm.Handler.XmlTypeName != MultiForm.Html.XmlTypeName)
            {
                message = "Unsupported root form type: " + rootForm.Handler.XmlTypeName;
                return false;
            }

            string rootHtmlXmlBeforeConversion = rootForm.RootElement.OuterXml;
            HashSet<string> controlNames = GetExistingControlNames(webPanel, forms);
            MultiForm_GetUniqueControlName getUniqueControlName = (baseName, _) => GetUniqueControlName(controlNames, baseName);
            XmlElement layoutRoot = MultiForm.Layout.CreateForm(getUniqueControlName);
            MultiForm.Layout.ConvertForm(webPanel, layoutRoot, rootForm.Handler, rootForm.RootElement, controlNames);
            string layoutRootXmlAfterConversion = layoutRoot.OuterXml;

            List<MultiFormSerializer.Form> newForms = new List<MultiFormSerializer.Form>();
            foreach (MultiFormSerializer.Form form in forms)
            {
                if (form.Id != rootFormId)
                {
                    newForms.Add(form);
                }
            }

            newForms.Add(new MultiFormSerializer.Form(rootFormId, MultiForm.Layout, layoutRoot));
            XmlDocument convertedDocument = MultiFormSerializer.SaveForms(rootFormId, newForms);
            int classReplacementCount = ApplyClassReplacements(webPanel, convertedDocument, classReplacements);
            int cdataTerminators = ReplaceInvalidCDataTerminators(convertedDocument);
            string convertedXml = ReplaceStoredReferenceIds(webPanel, convertedDocument.OuterXml);
            convertedXml = SanitizeEscapedCDataMarkers(convertedXml, ref cdataTerminators);
            convertedXml = SanitizeConvertedXml(webPanel, convertedXml, ref cdataTerminators);
            DumpXmlIfInvalid(webPanel, convertedXml, "Converted XML after var/att replacement");
            webForm.EditableContent = convertedXml;
            try
            {
#pragma warning disable 0612
                webForm.EditableToStored();
#pragma warning restore 0612
            }
            catch (Exception)
            {
                DumpConversionFailureContext(
                    webPanel,
                    "EditableToStored failure",
                    originalEditableContent,
                    editableXmlBeforeConversion,
                    rootHtmlXmlBeforeConversion,
                    layoutRootXmlAfterConversion,
                    convertedXml,
                    webForm.Document == null ? null : webForm.Document.OuterXml);
                throw;
            }

            message = "HTML root converted with WebLayoutHandler"
                + (resolvedStoredReferences ? " after StoredToEditable" : "")
                + (classReplacementCount > 0 ? ". Class replacements: " + classReplacementCount.ToString() : "")
                + (cdataTerminators > 0 ? ". Replaced CDATA terminators: " + cdataTerminators.ToString() : "");
            return true;
        }

        private static int ApplyClassReplacements(WebPanel webPanel, XmlDocument convertedDocument, Dictionary<string, string> replacements)
        {
            if (replacements.Count == 0)
            {
                return 0;
            }

            int changed = 0;
            ApplyClassReplacements(convertedDocument.DocumentElement, replacements, ref changed);
            if (changed > 0)
            {
                CommonServices.Output.AddLine(webPanel.Name + ": class replacements applied: " + changed.ToString());
            }

            return changed;
        }

        private static void ApplyClassReplacements(XmlNode node, Dictionary<string, string> replacements, ref int changed)
        {
            if (node == null)
            {
                return;
            }

            if (node.Attributes != null)
            {
                foreach (XmlAttribute attribute in node.Attributes)
                {
                    if (IsClassAttribute(attribute.Name) && replacements.ContainsKey(attribute.Value))
                    {
                        attribute.Value = replacements[attribute.Value];
                        changed += 1;
                    }
                }
            }

            foreach (XmlNode child in node.ChildNodes)
            {
                ApplyClassReplacements(child, replacements, ref changed);
            }
        }

        private static bool IsClassAttribute(string attributeName)
        {
            return string.Equals(attributeName, "class", StringComparison.OrdinalIgnoreCase)
                || string.Equals(attributeName, "cellClass", StringComparison.OrdinalIgnoreCase)
                || string.Equals(attributeName, "rowClass", StringComparison.OrdinalIgnoreCase)
                || string.Equals(attributeName, "selectedClass", StringComparison.OrdinalIgnoreCase)
                || string.Equals(attributeName, "unselectedClass", StringComparison.OrdinalIgnoreCase);
        }

        private static Dictionary<string, string> LoadClassReplacements()
        {
            Dictionary<string, string> replacements = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            string filePath = Path.Combine(UIServices.KB.CurrentKB.UserDirectory, "KBDoctorWebFormClassReplacements.csv");
            if (!File.Exists(filePath))
            {
                File.WriteAllLines(filePath, new[]
                {
                    "# SourceClass,TargetClass",
                    "BotonGrande,Button"
                });
                CommonServices.Output.AddLine("Created class replacement example file: " + filePath);
            }

            foreach (string line in File.ReadAllLines(filePath))
            {
                string trimmedLine = line.Trim();
                if (trimmedLine.Length == 0 || trimmedLine.StartsWith("#"))
                {
                    continue;
                }

                string[] parts = trimmedLine.Split(new[] { ',', ';' }, 2);
                if (parts.Length < 2)
                {
                    CommonServices.Output.AddWarningLine("Invalid class replacement line: " + line);
                    continue;
                }

                string sourceClass = parts[0].Trim();
                string targetClass = parts[1].Trim();
                if (sourceClass.Length == 0 || targetClass.Length == 0)
                {
                    CommonServices.Output.AddWarningLine("Invalid class replacement line: " + line);
                    continue;
                }

                replacements[sourceClass] = targetClass;
            }

            CommonServices.Output.AddLine("Loaded class replacements: " + replacements.Count.ToString() + " from " + filePath);
            return replacements;
        }

        private static string SanitizeEscapedCDataMarkers(string xml, ref int replacements)
        {
            if (string.IsNullOrEmpty(xml))
            {
                return xml;
            }

            replacements += CountOccurrences(xml, "&amp;lt;![CDATA[");
            replacements += CountOccurrences(xml, "]]&amp;gt;");
            replacements += CountOccurrences(xml, "&lt;![CDATA[");
            replacements += CountOccurrences(xml, "]]&gt;");

            return xml
                .Replace("&amp;lt;![CDATA[", "")
                .Replace("]]&amp;gt;", "")
                .Replace("&lt;![CDATA[", "")
                .Replace("]]&gt;", "");
        }

        private static void DumpConversionFailureContext(
            WebPanel webPanel,
            string stage,
            string originalEditableContent,
            string editableXmlBeforeConversion,
            string rootHtmlXmlBeforeConversion,
            string layoutRootXmlAfterConversion,
            string convertedXml,
            string currentDocumentXml)
        {
            IOutputService output = CommonServices.Output;
            output.AddErrorLine("WebForm conversion diagnostic for " + webPanel.Name + " - " + stage);
            output.AddLine("CDATA terminator counts: original="
                + CountOccurrences(originalEditableContent, "]]>").ToString()
                + ", editableBeforeConversion=" + CountOccurrences(editableXmlBeforeConversion, "]]>").ToString()
                + ", rootHtml=" + CountOccurrences(rootHtmlXmlBeforeConversion, "]]>").ToString()
                + ", layoutRoot=" + CountOccurrences(layoutRootXmlAfterConversion, "]]>").ToString()
                + ", converted=" + CountOccurrences(convertedXml, "]]>").ToString()
                + ", currentDocument=" + CountOccurrences(currentDocumentXml, "]]>").ToString());
            DumpXml(webPanel, originalEditableContent, "Original EditableContent");
            DumpXml(webPanel, editableXmlBeforeConversion, "After StoredToEditable before conversion");
            DumpXml(webPanel, rootHtmlXmlBeforeConversion, "Root HTML form passed to ConvertForm");
            DumpXml(webPanel, layoutRootXmlAfterConversion, "Layout root returned by ConvertForm");
            DumpXml(webPanel, convertedXml, "Converted XML assigned to EditableContent");
            DumpXml(webPanel, currentDocumentXml, "Current WebFormPart.Document");
        }

        private static int CountOccurrences(string text, string value)
        {
            if (string.IsNullOrEmpty(text) || string.IsNullOrEmpty(value))
            {
                return 0;
            }

            int count = 0;
            int index = 0;
            while ((index = text.IndexOf(value, index, StringComparison.Ordinal)) >= 0)
            {
                count += 1;
                index += value.Length;
            }

            return count;
        }

        private static string SanitizeConvertedXml(WebPanel webPanel, string xml, ref int cdataTerminators)
        {
            XmlDocument document = new XmlDocument();
            try
            {
                document.LoadXml(xml);
            }
            catch (XmlException)
            {
                DumpXml(webPanel, xml, "Invalid converted XML before CDATA terminator sanitation");
                throw;
            }

            int replacements = ReplaceInvalidCDataTerminators(document);
            cdataTerminators += replacements;
            return replacements == 0 ? xml : document.OuterXml;
        }

        private static int ReplaceInvalidCDataTerminators(XmlDocument document)
        {
            int replacements = 0;
            ReplaceInvalidCDataTerminators(document.DocumentElement, ref replacements);
            return replacements;
        }

        private static void ReplaceInvalidCDataTerminators(XmlNode node, ref int replacements)
        {
            if (node == null)
            {
                return;
            }

            if (node.Attributes != null)
            {
                foreach (XmlAttribute attribute in node.Attributes)
                {
                    if (ReplaceInvalidCDataTerminator(attribute))
                    {
                        replacements += 1;
                    }
                }
            }

            if (ReplaceInvalidCDataTerminator(node))
            {
                replacements += 1;
            }

            foreach (XmlNode child in node.ChildNodes)
            {
                ReplaceInvalidCDataTerminators(child, ref replacements);
            }
        }

        private static bool ReplaceInvalidCDataTerminator(XmlNode node)
        {
            if (node == null || node.Value == null || node.Value.IndexOf("]]>", StringComparison.Ordinal) < 0)
            {
                return false;
            }

            node.Value = node.Value.Replace("]]>", "]]&gt;");
            return true;
        }

        private static void DumpXmlIfInvalid(WebPanel webPanel, string xml, string stage)
        {
            try
            {
                XmlDocument validationDocument = new XmlDocument();
                validationDocument.LoadXml(xml);
            }
            catch (XmlException exception)
            {
                CommonServices.Output.AddErrorLine("Invalid XML in " + webPanel.Name + " - " + stage + ": " + exception.Message);
                DumpXml(webPanel, xml, stage);
                throw;
            }
        }

        private static void DumpXml(WebPanel webPanel, string xml, string stage)
        {
            IOutputService output = CommonServices.Output;
            output.AddLine("----- XML BEGIN " + webPanel.Name + " - " + stage + " -----");
            output.AddLine(xml ?? "<null>");
            output.AddLine("----- XML END " + webPanel.Name + " - " + stage + " -----");
        }

        private static string ReplaceStoredReferenceIds(WebPanel webPanel, string xml)
        {
            if (string.IsNullOrEmpty(xml))
            {
                return xml;
            }

            VariablesPart variables = webPanel.Parts.Get<VariablesPart>();
            xml = Regex.Replace(xml, @"var:(\d+)", match =>
            {
                int variableId;
                if (!int.TryParse(match.Groups[1].Value, out variableId) || variables == null)
                {
                    return match.Value;
                }

                Variable variable = variables.GetVariable(variableId);
                return variable == null ? match.Value : SecurityElement.Escape("&" + variable.Name);
            }, RegexOptions.IgnoreCase);

            KBModel model = webPanel.Model;
            xml = Regex.Replace(xml, @"att:(\d+)", match =>
            {
                int attributeId;
                if (!int.TryParse(match.Groups[1].Value, out attributeId))
                {
                    return match.Value;
                }

                Artech.Genexus.Common.Objects.Attribute attribute = Artech.Genexus.Common.Objects.Attribute.Get(model, attributeId);
                return attribute == null ? match.Value : SecurityElement.Escape(attribute.Name);
            }, RegexOptions.IgnoreCase);

            return xml;
        }

        private static bool ResolveStoredReferencesBeforeLayoutConversion(WebPanel webPanel, XmlDocument formDocument)
        {
            string xml = formDocument.OuterXml;
            if (xml.IndexOf("att:", StringComparison.OrdinalIgnoreCase) < 0 && xml.IndexOf("var:", StringComparison.OrdinalIgnoreCase) < 0)
            {
                return false;
            }

            WebFormEditable.StoredToEditable(webPanel, formDocument);
            return true;
        }

        private static HashSet<string> GetExistingControlNames(WebPanel webPanel, IEnumerable<MultiFormSerializer.Form> forms)
        {
            HashSet<string> controlNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (MultiFormSerializer.Form form in forms)
            {
                foreach (string controlName in form.Handler.GetControlNames(webPanel, form.RootElement))
                {
                    if (!string.IsNullOrEmpty(controlName))
                    {
                        controlNames.Add(controlName);
                    }
                }
            }

            return controlNames;
        }

        private static string GetUniqueControlName(HashSet<string> existingNames, string baseName)
        {
            if (string.IsNullOrEmpty(baseName))
            {
                baseName = "Layout";
            }

            string candidate = baseName;
            int suffix = 1;
            while (existingNames.Contains(candidate))
            {
                candidate = baseName + suffix.ToString();
                suffix += 1;
            }

            existingNames.Add(candidate);
            return candidate;
        }

        private static void ConvertDefaultResponsiveProperties()
        {
            KBModel kbModel = UIServices.KB.CurrentModel;
            IOutputService output = CommonServices.Output;
            WebPanelReference masterRef = (WebPanelReference)kbModel.GetPropertyValue("idMASTER_PAGE");
            ThemeWebReference themeReference = (ThemeWebReference)kbModel.GetPropertyValue(Properties.MODEL.DefaultTheme);
            string modelWebDF = kbModel.GetPropertyValueString(Properties.MODEL.WebFormDefaults_DisplayName);

            ForEachTransactionAndWebPanel(kbModel, obj =>
            {
                bool changed = false;
                string webDF = obj.GetPropertyValueString(Properties.TRN.WebFormDefaults);
                if (ObjectsHelper.isGenerated(obj))
                {
                    if (webDF == modelWebDF && obj.IsPropertyDefault(Properties.TRN.WebFormDefaults))
                    {
                        obj.SetPropertyValue(Properties.TRN.WebUserExperience, Properties.TRN.WebFormDefaults_Values.ResponsiveWebDesign);
                        obj.SetPropertyValue(Properties.TRN.WebUserExperience, Properties.TRN.WebFormDefaults_Values.PreviousVersionsCompatible);
                        changed = true;
                    }

                    WebPanelReference objmasterRef = (WebPanelReference)obj.GetPropertyValue(Properties.TRN.MasterPage);
                    if (objmasterRef.GetFullQualifyName(kbModel) == masterRef.GetFullQualifyName(kbModel) && obj.IsPropertyDefault(Properties.TRN.WebFormDefaults))
                    {
                        obj.SetPropertyValue(Properties.TRN.MasterPage, WebPanelReference.NoneRef);
                        obj.SetPropertyValue(Properties.TRN.MasterPage, objmasterRef);
                        changed = true;
                    }

                    ThemeWebReference objThemeRef = (ThemeWebReference)obj.GetPropertyValue(Properties.TRN.Theme);
                    if (objThemeRef.GetFullQualifiedName(kbModel) == themeReference.GetFullQualifiedName(kbModel) && obj.IsPropertyDefault(Properties.TRN.Theme))
                    {
                        obj.SetPropertyValue(Properties.TRN.Theme, themeReference);
                        changed = true;
                    }
                }

                if (changed)
                {
                    obj.Save();
                }
                output.AddLine(obj.Name);
            });
        }

        private static void ConvertDefaultWebUXToSmooth()
        {
            KBModel kbModel = UIServices.KB.CurrentModel;
            IOutputService output = CommonServices.Output;
            string modelWebUX = kbModel.GetPropertyValueString(Properties.MODEL.WebUserExperience);

            ForEachTransactionAndWebPanel(kbModel, obj =>
            {
                string webUX = obj.GetPropertyValueString(Properties.TRN.WebUserExperience);
                if (ObjectsHelper.isGenerated(obj) && webUX == modelWebUX && obj.IsPropertyDefault(Properties.TRN.WebUserExperience))
                {
                    obj.SetPropertyValue(Properties.TRN.WebUserExperience, Properties.TRN.WebUserExperience_Values.Smooth);
                    obj.SetPropertyValue(Properties.TRN.WebUserExperience, Properties.TRN.WebUserExperience_Values.PreviousVersionsCompatible);
                    obj.Save();
                }
                else
                {
                    output.AddText("NO CAMBIA WEBUX ");
                }

                output.AddLine(obj.Name);
            });
        }

        private static void ConvertGeneratedPreviousCompatibleToSmooth()
        {
            KBModel kbModel = UIServices.KB.CurrentModel;
            IOutputService output = CommonServices.Output;
            ForEachTransactionAndWebPanel(kbModel, obj =>
            {
                if (ObjectsHelper.isGenerated(obj) && ObjectsHelper.isGeneratedbyPattern(obj))
                {
                    string eventList = ListOfEvents(obj);
                    output.AddLine(obj.Name + "," + obj.GetPropertyValueString(Properties.TRN.WebUserExperience) + "," + eventList);
                    if (obj.GetPropertyValueString(Properties.TRN.WebUserExperience) == "Previous versions compatible")
                    {
                        obj.SetPropertyValue(Properties.TRN.WebUserExperience, Properties.TRN.WebUserExperience_Values.Smooth);
                        obj.Save();
                    }
                }
            });
        }

        private static void AuditSmoothResponsive()
        {
            KBModel kbModel = UIServices.KB.CurrentModel;
            IOutputService output = CommonServices.Output;
            QualifiedName qn = new QualifiedName("DECLARACIONES.Dua.HCIMDPol");
            WebPanel webp = WebPanel.Get(kbModel, qn);
            WebPanelReference luciamasterRef = webp == null ? null : (WebPanelReference)webp.GetPropertyValue(Properties.TRN.MasterPage);

            output.AddLine("ObjectName,UX,MasterPageName,Responsive,Theme,AbstracEditor,PatternOrManual,NeedFix");
            int objTotal = 0;
            int objToFix = 0;

            ForEachTransactionAndWebPanel(kbModel, obj =>
            {
                if (ObjectsHelper.isGenerated(obj))
                {
                    objTotal += 1;
                    string webUX = obj.GetPropertyValueString(Properties.TRN.WebUserExperience).ToUpper();
                    WebPanelReference objmasterRef = (WebPanelReference)obj.GetPropertyValue(Properties.TRN.MasterPage);
                    string webDF = obj.GetPropertyValueString(Properties.TRN.WebFormDefaults);
                    string themeObj = obj.GetPropertyValueString(Properties.TRN.Theme);
                    WebFormPart webFormPart = obj is WebPanel ? ((WebPanel)obj).WebForm : ((Transaction)obj).WebForm;
                    bool abstracEditor = WebPanelFormRootIsAbstract(webFormPart);
                    string genPatt = ObjectsHelper.isGeneratedbyPattern(obj) ? "Pattern" : "Manual";
                    bool needFix = webUX != "SMOOTH" || objmasterRef.GetName(kbModel) != "GIAMasterPage_v1" || webDF == "Previous versions compatible" || themeObj != "GIATheme_v1" || !abstracEditor;
                    if (needFix)
                    {
                        objToFix += 1;
                    }

                    output.AddLine(obj.Name + "," + webUX + "," + objmasterRef.GetName(kbModel) + "," + webDF + "," + themeObj + "," + abstracEditor.ToString() + "," + genPatt + "," + needFix.ToString());
                    if (luciamasterRef != null && objmasterRef.GetName(kbModel) == "GIAMasterPage_v1" && !abstracEditor && genPatt == "Manual")
                    {
                        output.AddLine(">>> Cambio " + obj.Name);
                        obj.SetPropertyValue(Properties.TRN.MasterPage, luciamasterRef);
                        obj.Save();
                    }
                }
            });

            output.AddLine("   ");
            output.AddLine("#Objects:" + objTotal.ToString() + "  #Objects to Fix: " + objToFix.ToString());
        }

        private static void ResetDefaultMasterPageReferences()
        {
            KBModel kbModel = UIServices.KB.CurrentModel;
            IOutputService output = CommonServices.Output;
            WebPanelReference masterRef = (WebPanelReference)kbModel.GetPropertyValue("idMASTER_PAGE");
            output.AddWarningLine(masterRef.GetName(kbModel));

            ForEachTransactionAndWebPanel(kbModel, obj =>
            {
                if (ObjectsHelper.isGenerated(obj))
                {
                    WebPanelReference objmasterRef = (WebPanelReference)obj.GetPropertyValue(Properties.TRN.MasterPage);
                    if (objmasterRef.GetFullQualifyName(kbModel) == masterRef.GetFullQualifyName(kbModel) && obj.IsPropertyDefault(Properties.TRN.WebFormDefaults))
                    {
                        obj.SetPropertyValue(Properties.TRN.MasterPage, WebPanelReference.NoneRef);
                        obj.SetPropertyValue(Properties.TRN.MasterPage, objmasterRef);
                        obj.Save();

                        string webUX = obj.GetPropertyValueString(Properties.TRN.WebUserExperience).ToUpper();
                        if (webUX == "SMOOTH")
                        {
                            output.AddLine("ERROR SMOOTH WITH MASTERPAGE DEFAULT:" + obj.Name + "--" + objmasterRef.GetFullQualifyName(kbModel));
                        }
                    }
                }
            });
        }

        private static void ForEachTransactionAndWebPanel(KBModel kbModel, Action<KBObject> action)
        {
            foreach (KBObject obj in Utility.EditableObjects(Transaction.GetAll(kbModel)))
            {
                action(obj);
            }

            foreach (KBObject obj in Utility.EditableObjects(WebPanel.GetAll(kbModel)))
            {
                action(obj);
            }
        }

        private static string ListOfEvents(KBObject obj)
        {
            string eventsList = "";
            string source = obj.Parts.Get<EventsPart>().Source;
            string sourceWOcomments = Utility.ExtractComments(source);
            bool containLOAD = false, containREFRESH = false, containSTART = false;

            using (StringReader reader = new StringReader(sourceWOcomments))
            {
                string line;
                while ((line = reader.ReadLine()) != null)
                {
                    if (line.ToUpper().StartsWith("EVENT "))
                    {
                        eventsList += "," + line.ToUpper().Replace("EVENT ", "");
                        if (line.ToUpper().Contains("LOAD"))
                            containLOAD = true;
                        if (line.ToUpper().Contains("REFRESH"))
                            containREFRESH = true;
                        if (line.ToUpper().Contains("START"))
                            containSTART = true;
                    }
                }
            }

            return "," + containSTART.ToString() + "," + containREFRESH.ToString() + "," + containLOAD.ToString() + eventsList;
        }

        private static bool WebPanelFormRootIsAbstract(WebFormPart part)
        {
            if (part.EditableContent != null)
            {
                XmlDocument xmlDocumentWebForm = new XmlDocument();
                xmlDocumentWebForm.LoadXml(part.EditableContent);
                return xmlDocumentWebForm.SelectSingleNode("//Form[@id='" + xmlDocumentWebForm.DocumentElement?.Attributes["rootId"]?.Value + "']")?.Attributes["type"]?.Value == "layout";
            }

            return part.Model.GetPropertyValue<Properties.MODEL.DefaultWebFormEditor_Enum>(Properties.MODEL.DefaultWebFormEditor) == Properties.MODEL.DefaultWebFormEditor_Enum.AbstractLayout;
        }
    }
}
