using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml;
using Artech.Architecture.Common.Descriptors;
using Artech.Architecture.Common.Objects;
using Artech.Architecture.Common.Services;
using Artech.Architecture.UI.Framework.Services;
using Artech.Genexus.Common;
using Artech.Genexus.Common.Objects;
using Artech.Genexus.Common.Parts;
using Artech.Genexus.Common.Parts.WebForm;
using Concepto.Packages.KBDoctorCore.Sources;

namespace Concepto.Packages.KBDoctor
{
    static class UIFrontendActions
    {
        private const string DefaultClassMarker = "*Default*";
        private const string RuleFileName = "KBDoctorControlClassRules.csv";

        public static void ImproveControlClasses()
        {
            string title = "KBDoctor - Improve control classes";
            IOutputService output = CommonServices.Output;
            KBDoctorOutput.StartSection(title);

            List<ControlClassRule> rules = LoadControlClassRules();
            SelectObjectOptions selectObjectOption = new SelectObjectOptions();
            selectObjectOption.MultipleSelection = true;
            selectObjectOption.ObjectTypes.Add(KBObjectDescriptor.Get<WebPanel>());

            List<WebPanel> webPanels = UIServices.SelectObjectDialog.SelectObjects(selectObjectOption).Cast<WebPanel>().ToList();
            string outputFile = Functions.CreateOutputFile(UIServices.KB, title);
            KBDoctorXMLWriter writer = new KBDoctorXMLWriter(outputFile, Encoding.UTF8);
            writer.AddHeader(title);
            writer.AddTableHeader(new[] { "Object", "Module", "Control", "ControlType", "OldClass", "NewClass", "Rule", "Action" });

            output.AddLine("Object,Module,Control,ControlType,OldClass,NewClass,Rule,Action");

            int selected = 0;
            int saved = 0;
            int skippedPattern = 0;
            int failed = 0;
            int reportRows = 0;

            foreach (WebPanel webPanel in webPanels)
            {
                selected += 1;
                string progress = "(" + selected.ToString() + "/" + webPanels.Count.ToString() + ") ";
                output.AddLine(progress + "Processing " + webPanel.Name);

                if (ObjectsHelper.isGeneratedbyPattern(webPanel))
                {
                    skippedPattern += 1;
                    AddReportRow(writer, webPanel, "", "", "", "", "", "Skipped: object generated by pattern");
                    reportRows += 1;
                    continue;
                }

                if (!Utility.IsUserEditableObject(webPanel))
                {
                    failed += 1;
                    AddReportRow(writer, webPanel, "", "", "", "", "", "Error: read-only object");
                    reportRows += 1;
                    continue;
                }

                try
                {
                    List<ControlClassChange> changes = ApplyControlClassRules(webPanel, rules);
                    if (changes.Count > 0)
                    {
                        webPanel.Save();
                        saved += 1;
                    }

                    foreach (ControlClassChange change in changes)
                    {
                        AddReportRow(writer, webPanel, change.ControlName, change.ControlType, change.OldClass, change.NewClass, change.Rule, "Changed");
                        output.AddLine(webPanel.Name + "," + (webPanel.Module == null ? "" : webPanel.Module.Name) + "," + change.ControlName + "," + change.ControlType + "," + change.OldClass + "," + change.NewClass + "," + change.Rule + ",Changed");
                        reportRows += 1;
                    }
                }
                catch (Exception e)
                {
                    failed += 1;
                    output.AddErrorLine("Improve control classes failed for " + webPanel.Name + ": " + e.ToString());
                    AddReportRow(writer, webPanel, "", "", "", "", "", "Error: " + e.Message);
                    reportRows += 1;
                }
            }

            writer.AddFooter();
            writer.Close();
            output.AddLine("");
            output.AddLine("Selected: " + selected.ToString()
                + ". Saved: " + saved.ToString()
                + ". Skipped pattern generated: " + skippedPattern.ToString()
                + ". Failed: " + failed.ToString()
                + ". Report rows: " + reportRows.ToString() + ".");
            output.AddLine("Report: " + outputFile);
            KBDoctorHelper.ShowKBDoctorResults(outputFile);

            KBDoctorOutput.EndSection(title, true);
        }

        private static List<ControlClassChange> ApplyControlClassRules(WebPanel webPanel, List<ControlClassRule> rules)
        {
            List<ControlClassChange> changes = new List<ControlClassChange>();
            WebFormPart webForm = webPanel.WebForm;
            if (webForm == null || string.IsNullOrEmpty(webForm.EditableContent))
            {
                return changes;
            }

            XmlDocument document = new XmlDocument();
            document.LoadXml(webForm.EditableContent);

            foreach (XmlElement element in document.SelectNodes("//*").OfType<XmlElement>())
            {
                ApplyReplaceClassRules(element, rules, changes);
            }

            foreach (XmlElement element in document.SelectNodes("//*").OfType<XmlElement>())
            {
                string controlType = GetControlType(element);
                if (string.IsNullOrEmpty(controlType))
                {
                    continue;
                }

                GridMetrics metrics = IsGridElement(element) ? GetGridMetrics(webPanel, element) : GridMetrics.Empty;
                ControlClassRule matchedRule = null;
                foreach (ControlClassRule rule in rules.Where(rule => rule.Kind == ControlClassRuleKind.ControlType))
                {
                    if (TextEquals(rule.Selector, controlType) && RuleConditionMatches(rule.Condition, metrics))
                    {
                        matchedRule = rule;
                    }
                }

                if (matchedRule != null)
                {
                    ApplyClass(element, matchedRule.TargetClass, GetControlName(element), controlType, matchedRule.ToString(), changes);
                }
            }

            foreach (XmlElement grid in document.SelectNodes("//*").OfType<XmlElement>().Where(IsGridElement))
            {
                ApplyGridColumnRules(webPanel, grid, rules, changes);
            }

            if (changes.Count > 0)
            {
                webForm.EditableContent = document.OuterXml;
            }

            return changes;
        }

        private static void ApplyReplaceClassRules(XmlElement element, List<ControlClassRule> rules, List<ControlClassChange> changes)
        {
            XmlAttribute classAttribute = GetClassAttribute(element, false);
            if (classAttribute == null || string.IsNullOrEmpty(classAttribute.Value))
            {
                return;
            }

            string currentClass = classAttribute.Value;
            ControlClassRule matchedRule = null;
            foreach (ControlClassRule rule in rules.Where(rule => rule.Kind == ControlClassRuleKind.ReplaceClass))
            {
                if (TextEquals(rule.Selector, currentClass))
                {
                    matchedRule = rule;
                }
            }

            if (matchedRule != null)
            {
                ApplyClass(element, matchedRule.TargetClass, GetControlName(element), GetControlType(element), matchedRule.ToString(), changes);
            }
        }

        private static void ApplyGridColumnRules(WebPanel webPanel, XmlElement grid, List<ControlClassRule> rules, List<ControlClassChange> changes)
        {
            List<ControlClassRule> columnRules = rules.Where(rule => rule.Kind == ControlClassRuleKind.GridColumn).ToList();
            if (columnRules.Count == 0)
            {
                return;
            }

            foreach (XmlElement column in GetColumnElements(grid))
            {
                FieldInfo field = ResolveColumnField(webPanel, column);
                ControlClassRule matchedRule = columnRules.FirstOrDefault(rule => TextEquals(rule.Condition, "IsImage") && field.IsImage)
                    ?? columnRules.FirstOrDefault(rule => IsCharLengthCondition(rule.Condition, out int minLength) && field.IsCharacter && field.Length > minLength)
                    ?? columnRules.FirstOrDefault(rule => TextEquals(rule.Condition, "Default") || string.IsNullOrEmpty(rule.Condition));

                if (matchedRule != null)
                {
                    ApplyColumnClass(column, matchedRule.TargetClass, GetControlName(column), matchedRule.ToString(), changes);
                }
            }
        }

        private static void ApplyClass(XmlElement element, string newClass, string controlName, string controlType, string rule, List<ControlClassChange> changes)
        {
            XmlAttribute classAttribute = GetClassAttribute(element, !TextEquals(newClass, DefaultClassMarker));
            string oldClass = classAttribute == null ? "" : classAttribute.Value;
            if (TextEquals(newClass, DefaultClassMarker))
            {
                if (classAttribute == null)
                {
                    return;
                }

                element.Attributes.Remove(classAttribute);
                changes.Add(new ControlClassChange(controlName, controlType, oldClass, DefaultClassMarker, rule));
                return;
            }

            if (classAttribute == null || string.Equals(oldClass, newClass, StringComparison.Ordinal))
            {
                return;
            }

            classAttribute.Value = newClass;
            changes.Add(new ControlClassChange(controlName, controlType, oldClass, newClass, rule));
        }

        private static void ApplyColumnClass(XmlElement column, string newClass, string controlName, string rule, List<ControlClassChange> changes)
        {
            XmlAttribute classAttribute = GetPreferredColumnClassAttribute(column, !TextEquals(newClass, DefaultClassMarker));
            string oldClass = classAttribute == null ? "" : classAttribute.Value;
            if (TextEquals(newClass, DefaultClassMarker))
            {
                if (classAttribute == null)
                {
                    return;
                }

                column.Attributes.Remove(classAttribute);
                changes.Add(new ControlClassChange(controlName, "GridColumn", oldClass, DefaultClassMarker, rule));
                return;
            }

            if (classAttribute == null || string.Equals(oldClass, newClass, StringComparison.Ordinal))
            {
                return;
            }

            classAttribute.Value = newClass;
            changes.Add(new ControlClassChange(controlName, "GridColumn", oldClass, newClass, rule));
        }

        private static XmlAttribute GetClassAttribute(XmlElement element, bool create)
        {
            XmlAttribute attribute = FindAttribute(element, "class") ?? FindAttribute(element, "Class");
            if (attribute == null && create)
            {
                attribute = element.OwnerDocument.CreateAttribute("class");
                element.Attributes.Append(attribute);
            }

            return attribute;
        }

        private static XmlAttribute GetPreferredColumnClassAttribute(XmlElement column, bool create)
        {
            XmlAttribute attribute = FindAttribute(column, "cellClass") ?? FindAttribute(column, "class") ?? FindAttribute(column, "Class");
            if (attribute == null && create)
            {
                attribute = column.OwnerDocument.CreateAttribute("cellClass");
                column.Attributes.Append(attribute);
            }

            return attribute;
        }

        private static XmlAttribute FindAttribute(XmlElement element, string name)
        {
            foreach (XmlAttribute attribute in element.Attributes)
            {
                if (string.Equals(attribute.Name, name, StringComparison.OrdinalIgnoreCase))
                {
                    return attribute;
                }
            }

            return null;
        }

        private static string GetControlType(XmlElement element)
        {
            string value = GetAttributeValue(element, "ControlType");
            if (!string.IsNullOrEmpty(value))
            {
                return NormalizeControlType(value);
            }

            return NormalizeControlType(element.Name);
        }

        private static string NormalizeControlType(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return "";
            }

            string normalized = value.Trim();
            if (normalized.IndexOf("Grid", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                return "Grid";
            }

            if (normalized.IndexOf("Button", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                return "Button";
            }

            return normalized;
        }

        private static string GetControlName(XmlElement element)
        {
            return GetAttributeValue(element, "ControlName")
                ?? GetAttributeValue(element, "Name")
                ?? GetAttributeValue(element, "name")
                ?? element.Name;
        }

        private static string GetAttributeValue(XmlElement element, string attributeName)
        {
            XmlAttribute attribute = FindAttribute(element, attributeName);
            return attribute == null ? null : attribute.Value;
        }

        private static bool IsGridElement(XmlElement element)
        {
            return TextEquals(GetControlType(element), "Grid") || element.Name.IndexOf("Grid", StringComparison.OrdinalIgnoreCase) >= 0;
        }

        private static IEnumerable<XmlElement> GetColumnElements(XmlElement grid)
        {
            return grid.SelectNodes(".//*")
                .OfType<XmlElement>()
                .Where(element => element.Name.IndexOf("Column", StringComparison.OrdinalIgnoreCase) >= 0 || TextEquals(GetControlType(element), "Column"));
        }

        private static GridMetrics GetGridMetrics(WebPanel webPanel, XmlElement grid)
        {
            int count = 0;
            int lengthSum = 0;
            foreach (XmlElement column in GetColumnElements(grid))
            {
                count += 1;
                FieldInfo field = ResolveColumnField(webPanel, column);
                lengthSum += field.Length;
            }

            return new GridMetrics(count, lengthSum);
        }

        private static FieldInfo ResolveColumnField(WebPanel webPanel, XmlElement column)
        {
            string xml = column.OuterXml;
            Match attributeIdMatch = Regex.Match(xml, @"att:(\d+)", RegexOptions.IgnoreCase);
            if (attributeIdMatch.Success && int.TryParse(attributeIdMatch.Groups[1].Value, out int attributeId))
            {
                Artech.Genexus.Common.Objects.Attribute attribute = Artech.Genexus.Common.Objects.Attribute.Get(webPanel.Model, attributeId);
                return FieldInfo.FromAttribute(attribute);
            }

            foreach (XmlAttribute attribute in column.Attributes)
            {
                FieldInfo field = ResolveFieldByName(webPanel, attribute.Value);
                if (field.Found)
                {
                    return field;
                }
            }

            return FieldInfo.Unknown;
        }

        private static FieldInfo ResolveFieldByName(WebPanel webPanel, string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return FieldInfo.Unknown;
            }

            string name = value.Trim().Trim('&');
            if (name.Length == 0)
            {
                return FieldInfo.Unknown;
            }

            Artech.Genexus.Common.Objects.Attribute attribute = Artech.Genexus.Common.Objects.Attribute.Get(webPanel.Model, name);
            if (attribute != null)
            {
                return FieldInfo.FromAttribute(attribute);
            }

            VariablesPart variables = webPanel.Parts.Get<VariablesPart>();
            if (variables != null)
            {
                Variable variable = variables.GetVariable(name);
                if (variable != null)
                {
                    return FieldInfo.FromVariable(variable);
                }
            }

            return FieldInfo.Unknown;
        }

        private static bool RuleConditionMatches(string condition, GridMetrics metrics)
        {
            if (string.IsNullOrEmpty(condition) || TextEquals(condition, "Default"))
            {
                return true;
            }

            Match lengthMatch = Regex.Match(condition, @"(?i)^ColumnLengthSum\s*>\s*(\d+)$");
            if (lengthMatch.Success && int.TryParse(lengthMatch.Groups[1].Value, out int minLength))
            {
                return metrics.ColumnLengthSum > minLength;
            }

            Match countMatch = Regex.Match(condition, @"(?i)^ColumnCount\s*>\s*(\d+)$");
            if (countMatch.Success && int.TryParse(countMatch.Groups[1].Value, out int minCount))
            {
                return metrics.ColumnCount > minCount;
            }

            return false;
        }

        private static bool IsCharLengthCondition(string condition, out int minLength)
        {
            minLength = 0;
            Match match = Regex.Match(condition ?? "", @"(?i)^CharLength\s*>\s*(\d+)$");
            return match.Success && int.TryParse(match.Groups[1].Value, out minLength);
        }

        private static List<ControlClassRule> LoadControlClassRules()
        {
            string filePath = Path.Combine(UIServices.KB.CurrentKB.UserDirectory, RuleFileName);
            if (!File.Exists(filePath))
            {
                File.WriteAllLines(filePath, new[]
                {
                    "# Kind,Selector,Condition,TargetClass",
                    "# Kinds: ReplaceClass, ControlType, GridColumn",
                    "# TargetClass can be *Default* to remove an explicit class.",
                    "ReplaceClass,NombreTitulo,,AttributeTitle",
                    "ControlType,Button,,Button",
                    "ControlType,Grid,,WW__Grid",
                    "ControlType,Grid,ColumnLengthSum>200,WW__Grid_HorizontalScroll",
                    "ControlType,Grid,ColumnCount>12,Grid_Compacto",
                    "GridColumn,*,CharLength>150,column_wider",
                    "GridColumn,*,IsImage,column_action",
                    "GridColumn,*,Default,column"
                });
                CommonServices.Output.AddLine("Created control class rules example file: " + filePath);
            }

            List<ControlClassRule> rules = new List<ControlClassRule>();
            foreach (string line in File.ReadAllLines(filePath))
            {
                string trimmed = line.Trim();
                if (trimmed.Length == 0 || trimmed.StartsWith("#"))
                {
                    continue;
                }

                string[] parts = trimmed.Split(new[] { ',', ';' }, 4);
                if (parts.Length < 4)
                {
                    CommonServices.Output.AddWarningLine("Invalid control class rule line: " + line);
                    continue;
                }

                if (!Enum.TryParse(parts[0].Trim(), true, out ControlClassRuleKind kind))
                {
                    CommonServices.Output.AddWarningLine("Invalid control class rule kind: " + line);
                    continue;
                }

                rules.Add(new ControlClassRule(kind, parts[1].Trim(), parts[2].Trim(), parts[3].Trim()));
            }

            CommonServices.Output.AddLine("Loaded control class rules: " + rules.Count.ToString() + " from " + filePath);
            return rules;
        }

        private static void AddReportRow(KBDoctorXMLWriter writer, WebPanel webPanel, string controlName, string controlType, string oldClass, string newClass, string rule, string action)
        {
            writer.AddTableData(new[]
            {
                Functions.linkObject(webPanel),
                Html(webPanel.Module == null ? "" : webPanel.Module.Name),
                Html(controlName),
                Html(controlType),
                Html(oldClass),
                Html(newClass),
                Html(rule),
                Html(action)
            });
        }

        private static string Html(string text)
        {
            return SecurityElement.Escape(text ?? "");
        }

        private static bool TextEquals(string left, string right)
        {
            return string.Equals(left ?? "", right ?? "", StringComparison.OrdinalIgnoreCase);
        }

        private enum ControlClassRuleKind
        {
            ReplaceClass,
            ControlType,
            GridColumn
        }

        private class ControlClassRule
        {
            public ControlClassRule(ControlClassRuleKind kind, string selector, string condition, string targetClass)
            {
                Kind = kind;
                Selector = selector;
                Condition = condition;
                TargetClass = targetClass;
            }

            public ControlClassRuleKind Kind { get; }
            public string Selector { get; }
            public string Condition { get; }
            public string TargetClass { get; }

            public override string ToString()
            {
                return Kind.ToString() + " " + Selector + (string.IsNullOrEmpty(Condition) ? "" : " & " + Condition) + " -> " + TargetClass;
            }
        }

        private class ControlClassChange
        {
            public ControlClassChange(string controlName, string controlType, string oldClass, string newClass, string rule)
            {
                ControlName = controlName;
                ControlType = controlType;
                OldClass = oldClass;
                NewClass = newClass;
                Rule = rule;
            }

            public string ControlName { get; }
            public string ControlType { get; }
            public string OldClass { get; }
            public string NewClass { get; }
            public string Rule { get; }
        }

        private class GridMetrics
        {
            public static readonly GridMetrics Empty = new GridMetrics(0, 0);

            public GridMetrics(int columnCount, int columnLengthSum)
            {
                ColumnCount = columnCount;
                ColumnLengthSum = columnLengthSum;
            }

            public int ColumnCount { get; }
            public int ColumnLengthSum { get; }
        }

        private class FieldInfo
        {
            public static readonly FieldInfo Unknown = new FieldInfo(false, false, false, 0);

            private FieldInfo(bool found, bool isCharacter, bool isImage, int length)
            {
                Found = found;
                IsCharacter = isCharacter;
                IsImage = isImage;
                Length = length;
            }

            public bool Found { get; }
            public bool IsCharacter { get; }
            public bool IsImage { get; }
            public int Length { get; }

            public static FieldInfo FromAttribute(Artech.Genexus.Common.Objects.Attribute attribute)
            {
                if (attribute == null)
                {
                    return Unknown;
                }

                return FromType(attribute.Type.ToString(), attribute.Length);
            }

            public static FieldInfo FromVariable(Variable variable)
            {
                if (variable == null)
                {
                    return Unknown;
                }

                return FromType(variable.Type.ToString(), variable.Length);
            }

            private static FieldInfo FromType(string type, int length)
            {
                bool isCharacter = type.IndexOf("CHAR", StringComparison.OrdinalIgnoreCase) >= 0
                    || type.IndexOf("VARCHAR", StringComparison.OrdinalIgnoreCase) >= 0
                    || type.IndexOf("LONGVARCHAR", StringComparison.OrdinalIgnoreCase) >= 0;
                bool isImage = type.IndexOf("IMAGE", StringComparison.OrdinalIgnoreCase) >= 0
                    || type.IndexOf("BINARY", StringComparison.OrdinalIgnoreCase) >= 0
                    || type.IndexOf("BLOB", StringComparison.OrdinalIgnoreCase) >= 0;
                return new FieldInfo(true, isCharacter, isImage, length);
            }
        }
    }
}
